/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
export { default as AddLine } from "./AddLine";
export { default as ArrowLeftRightLine } from "./ArrowLeftRightLine";
export { default as BookmarkFill } from "./BookmarkFill";
export { default as BookmarkLine } from "./BookmarkLine";
export { default as CloseLine } from "./CloseLine";
export { default as Copy } from "./Copy";
export { default as DeleteBinFill } from "./DeleteBinFill";
export { default as DeleteBinLine } from "./DeleteBinLine";
export { default as FileCopyFill } from "./FileCopyFill";
export { default as FileCopyLine } from "./FileCopyLine";
export { default as FileMarkedFill } from "./FileMarkedFill";
export { default as FileMarkedLine } from "./FileMarkedLine";
export { default as Forward15Line } from "./Forward15Line";
export { default as HeartFill } from "./HeartFill";
export { default as HeartLine } from "./HeartLine";
export { default as MenuLine } from "./MenuLine";
export { default as PencilFill } from "./PencilFill";
export { default as PencilLine } from "./PencilLine";
export { default as RemoveCircle } from "./RemoveCircle";
export { default as Replay15Line } from "./Replay15Line";
export { default as Reply } from "./Reply";
export { default as SubtractLine } from "./SubtractLine";
export { default as Thumb } from "./Thumb";
export { default as ThumbFilled } from "./ThumbFilled";
