name: "Vercel Deploy"
description: "Deploys to Vercel"
inputs:
  VERCEL_TOKEN:
    description: "Vercel API token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install Vercel CLI"
      shell: bash
      run: npm install --global vercel
    - name: "Pull vercel info"
      shell: bash
      run: vercel pull --yes --environment=preview --token=${{ inputs.VERCEL_TOKEN }}
    - name: "Build vercel"
      shell: bash
      run: vercel build --token=${{ inputs.VERCEL_TOKEN }}
    - name: Mark pending
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'pending',
            context: 'vercel-deploy',
            description: 'Deployment in progress'
          })
    - name: "Deploy vercel"
      shell: bash
      id: deploy
      run: echo "DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ inputs.VERCEL_TOKEN }})" >> "$GITHUB_OUTPUT"
    - name: Mark success
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'vercel-deploy',
            description: 'Deployment successful',
            target_url: '${{ steps.deploy.outputs.DEPLOYMENT_URL }}'
          })
    - name: "Create alias"
      shell: bash
      id: "alias"
      continue-on-error: true
      run: |
        if [ ${{github.ref}} == 'refs/heads/master' ]; then
          ALIAS="designmanual.ndla.no"
        else
          ALIAS="frontend-packages-${{ github.event.number }}.vercel.app"
        fi
        vercel alias --token=${{ inputs.VERCEL_TOKEN }} ${{ steps.deploy.outputs.DEPLOYMENT_URL }} $ALIAS
        echo "ALIAS=$ALIAS" >> "$GITHUB_OUTPUT"
    - name: "Update deploy status"
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            context: 'vercel-deploy',
            description: 'Alias successful',
            target_url: 'https://${{ steps.alias.outputs.ALIAS }}'
          })
