/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Copyright = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Creative Commons" viewBox="0 0 64 64" {...props}>
    <path d="M31.9 0a31 31 0 0 1 22.9 9.4A31.1 31.1 0 0 1 64 32c0 4.4-.8 8.5-2.3 12.3s-3.8 7.2-6.8 10.1A33 33 0 0 1 32 64a31.1 31.1 0 0 1-22.5-9.4 31.6 31.6 0 0 1 0-45.3A30.3 30.3 0 0 1 31.9 0m.2 5.8a25 25 0 0 0-18.5 7.7C11.1 16 9.2 18.8 7.8 22s-2 6.5-2 10A26.1 26.1 0 0 0 42 56.1c3.2-1.3 6.1-3.3 8.7-5.8 5-4.9 7.5-11 7.5-18.3a25.4 25.4 0 0 0-7.6-18.6 25.2 25.2 0 0 0-18.5-7.6m13.3 18.1L39 27.3c-.7-1.4-1.5-2.4-2.5-3s-1.9-.9-2.8-.9c-4.3 0-6.4 2.8-6.4 8.5 0 2.6.5 4.6 1.6 6.2a5.6 5.6 0 0 0 4.8 2.3c2.8 0 4.8-1.4 5.9-4.1l5.9 3c-1.3 2.4-3 4.2-5.2 5.5s-4.7 2-7.4 2c-4.3 0-7.8-1.3-10.4-4a15 15 0 0 1-4-11c0-4.6 1.3-8.2 4-10.9s6-4 10.1-4c6 .1 10.2 2.4 12.8 7" />
  </Icon>
);
export default Copyright;
