/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Nc = (props: Props) => (
  <Icon xmlSpace="preserve" data-license="CC-BY 4.0" data-source="Creative Commons" viewBox="5.5 -3.5 64 64" {...props}>
    <circle cx={37.5} cy={28.7} r={29.5} fill="none" />
    <path d="M37.4-3.5c9 0 16.6 3 22.8 9.3a30.8 30.8 0 0 1 9.3 22.7c0 9-3 16.5-9.1 22.5a31.6 31.6 0 0 1-45.5 0 30.7 30.7 0 0 1-9.4-22.5c0-8.8 3.1-16.3 9.4-22.7a30.6 30.6 0 0 1 22.5-9.3M12.7 19.9c-1 2.6-1.4 5.5-1.4 8.6 0 7 2.6 13.2 7.7 18.4a25.5 25.5 0 0 0 18.6 7.7c7.2 0 13.4-2.6 18.6-7.8 1.9-1.8 3.3-3.7 4.4-5.6l-12-5.4a9 9 0 0 1-3.1 5c-1.7 1.2-3.6 2-5.8 2.2v4.9H36v-5c-3.5 0-6.8-1.3-9.7-3.8l4.4-4.4c2 2 4.5 2.9 7.1 2.9 1.1 0 2-.3 2.9-.8.8-.5 1.1-1.3 1.1-2.4 0-.8-.2-1.5-.8-2l-3.1-1.3-3.8-1.7-5-2.2zM37.6 2.2A25 25 0 0 0 19 10a30.6 30.6 0 0 0-3.5 4.3l12.2 5.5c.5-1.7 1.5-3 3-4S34 14 36 14V9h3.7v5c3 .1 5.6 1.1 8 3l-4.1 4.2a9.5 9.5 0 0 0-5.5-1.8 6 6 0 0 0-2.7.5c-.8.4-1.2 1-1.2 2l.3.8 4 1.8 2.9 1.3 5.1 2.2L63 35.4c.6-2.3.8-4.6.8-6.9a25 25 0 0 0-7.6-18.6 25 25 0 0 0-18.5-7.7z" />
  </Icon>
);
export default Nc;
