/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Zero = (props: Props) => (
  <Icon xmlSpace="preserve" data-license="CC-BY 4.0" data-source="Creative Commons" viewBox="-0.5 0.5 64 64" {...props}>
    <circle cx={31.3} cy={32.9} r={30.1} fill="none" />
    <path d="M31.5 14c-10.6 0-13.2 10-13.2 18.5s2.6 18.4 13.2 18.4 13.2-10 13.2-18.4c0-8.5-2.6-18.4-13.2-18.4zm0 7c.4 0 .8 0 1.2.2.7.6 1.1 1.5.4 2.8l-7 13c-.3-1.7-.3-3.3-.3-4.5 0-3.7.3-11.5 5.7-11.5m5.3 6c.3 2 .4 4 .4 5.5 0 3.7-.3 11.5-5.7 11.5a4.9 4.9 0 0 1-1.7-.3c-1.2-.6-2-1.5-.9-3.1z" />
    <path d="M31.4.5a32.5 32.5 0 0 0-32 32A31.4 31.4 0 0 0 9 55.1a31.6 31.6 0 0 0 34.9 7 32.9 32.9 0 0 0 17.4-17.3c1.5-3.8 2.3-8 2.3-12.3a32.5 32.5 0 0 0-9.2-22.6 31.6 31.6 0 0 0-23-9.4m.2 5.8C38.8 6.3 45 8.8 50 14a25.7 25.7 0 0 1 7.6 18.5c0 7.4-2.5 13.5-7.5 18.3a27.5 27.5 0 0 1-18.6 7.8A26 26 0 0 1 7.3 42.4 25.6 25.6 0 0 1 13 14c5-5 11.2-7.6 18.5-7.6z" />
  </Icon>
);
export default Zero;
