/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const AlignCenter = props => (
  <Icon viewBox="0 0 32 32" data-license="CC-BY 4.0" {...props}>
    <g>
      <path d="M0 2h32v4h-32zM6 8h20v4h-20zM6 20h20v4h-20zM0 14h32v4h-32zM0 26h32v4h-32z" />
    </g>
  </Icon>
);

export default AlignCenter;
