/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const AlignLeft = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M3 4h18v2H3zm0 15h14v2H3zm0-5h18v2H3zm0-5h14v2H3z" />
  </Icon>
);
export default AlignLeft;
