/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const CloudUploadOutline = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M19.4 10a7.5 7.5 0 0 0-14-2A6 6 0 0 0 0 14a6 6 0 0 0 6 6h13a5 5 0 0 0 5-5 5 5 0 0 0-4.6-5m-.4 8H6a4 4 0 0 1-4-4 4 4 0 0 1 3.6-4h1l.5-1a5.5 5.5 0 0 1 10.3 1.4l.3 1.5 1.5.1a3 3 0 0 1 2.8 3 3 3 0 0 1-3 3M8 13h2.6v3h2.8v-3H16l-4-4z" />
  </Icon>
);
export default CloudUploadOutline;
