/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const Code = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path fill="none" d="M0 0h24v24H0z" />
    <path d="M9.4 16.6 4.8 12l4.6-4.6L8 6l-6 6 6 6zm5.2 0 4.6-4.6-4.6-4.6L16 6l6 6-6 6z" />
  </Icon>
);
export default Code;
