/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const Concept = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M5.48 7.16a.75.75 0 0 0 0 1.5h13.04a.75.75 0 0 0 0-1.5zm0 3.09a.75.75 0 0 0 0 1.5h13.04a.75.75 0 0 0 0-1.5zm0 2.93a.75.75 0 0 0 0 1.5h13.04a.75.75 0 0 0 0-1.5z" />
    <path
      fillRule="evenodd"
      d="M9.35 19 12 23l2.65-4H20c.55 0 1.02-.2 1.41-.59A1.93 1.93 0 0 0 22 17V5c0-.55-.2-1.02-.59-1.41A1.93 1.93 0 0 0 20 3H4c-.55 0-1.02.2-1.41.59A1.93 1.93 0 0 0 2 5v12c0 .55.2 1.02.59 1.41.39.4.86.59 1.41.59zM20 17H4V5h16z"
      clipRule="evenodd"
    />
  </Icon>
);
export default Concept;
