/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon from '../Icon';

interface Props {
  children?: ReactNode;
}

const Concept = (props: Props) => (
  <Icon
    title="Concept"
    viewBox="0 0 47 54.9"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <rect x="9" y="30" width="29" height="2" />
      <rect x="9" y="21" width="29" height="2" />
      <rect x="9" y="12" width="29" height="2" />
      <path d="M45,0H2A2,2,0,0,0,0,1.9v38a1.9,1.9,0,0,0,2,1.9H15.8l.5.2,5.9,12.1a1.6,1.6,0,0,0,1.3.8h0a1.7,1.7,0,0,0,1.4-.9l5.8-12a1.1,1.1,0,0,1,.6-.3H45a2,2,0,0,0,2-1.9V1.8A2,2,0,0,0,45,0ZM31.2,39.8a2.7,2.7,0,0,0-2.3,1.4L23.5,52.3,18.1,41.1a2.6,2.6,0,0,0-2.3-1.3H2V2H45V39.8Z" />
    </g>
  </Icon>
);

export default Concept;
