/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const DetailSearch = (props: Props) => (
  <Icon viewBox="0 0 55.9 47" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="m27.7 17.7-7.7.2-.2-7.7v-.3h-2v.3l.2 7.7-7.7.2H10v2h.3l7.7-.2.2 7.7v.3h2v-.3l-.2-7.7 7.7-.2h.3v-2h-.3z" />
      <path d="M55.9 41.3a1.9 1.9 0 0 0-.7-1.1L36.3 26.9h-.1a23.2 23.2 0 0 0 1.3-3.7 18.9 18.9 0 0 0-2.4-14.3A18.7 18.7 0 0 0 23.2.5 18.7 18.7 0 0 0 .5 14.7a18.8 18.8 0 0 0 14.3 22.7 20.1 20.1 0 0 0 4.2.5 19.2 19.2 0 0 0 12.4-4.6h.1l19 13.3a1.7 1.7 0 0 0 1 .3 1.7 1.7 0 0 0 1.4-.7l2.8-3.7a2 2 0 0 0 .2-1.2Zm-40.7-5.8A17 17 0 1 1 33.4 9.8a17 17 0 0 1-18.2 25.7Zm36.2 9.4L33 31.9a31.5 31.5 0 0 0 2.2-2.9l.2-.3 18.5 12.9Z" />
    </g>
  </Icon>
);

export default DetailSearch;
