/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const ExpandableBox = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 23 29" {...props}>
    <g fill="none" stroke="#343434">
      <path d="M1.5 4.8H22v18.5H1.5z" />
      <path
        fill="#FFF"
        d="M10.6 20H16c.6 0 .8.4.5.8L15 23.4l-1 1.7-1.7 2.6c-.3.4-.8.4-1 0L9.4 25l-1-1.7-1.7-2.6c-.3-.4 0-.8.5-.8h3.3Zm2.1-11H7.3c-.6 0-.8-.4-.5-.8l1.6-2.6 1.1-1.7 1.6-2.6c.3-.4.8-.4 1.1 0L13.8 4 15 5.6l1.6 2.6c.3.4 0 .8-.5.8h-3.3Z"
      />
    </g>
  </Icon>
);
export default ExpandableBox;
