/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const ExpandDiagonalLine = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M17.59 5H14V3h7v7h-2V6.41l-4.3 4.3-1.4-1.42zM3 14h2v3.59l4.3-4.3 1.4 1.42L6.42 19H10v2H3z" />
  </Icon>
);
export default ExpandDiagonalLine;
