/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const Expandable = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path fill="none" d="M0 0h24v24H0z" />
      <path d="M12 5.8 15.2 9l1.4-1.4L12 3 7.4 7.6 8.8 9 12 5.8zm0 12.4L8.8 15l-1.4 1.4L12 21l4.6-4.6-1.4-1.4-3.2 3.2z" />
    </g>
  </Icon>
);

export default Expandable;
