/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const FactBox = (props: Props) => (
  <Icon viewBox="0 0 30 23" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path
        fill="#444"
        stroke="#444"
        d="M7 7.8h16.6M15 20l-3-6h6l-3 6zM.5.5v16-16zm0 16h10M.5.5h29m0 0v16m0 0h-10M15 22a5 5 0 1 0 0-10 5 5 0 0 0 0 10z"
      />
    </g>
  </Icon>
);

export default FactBox;
