/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const FocalPoint = props => (
  <Icon
    viewBox="0 0 32 32"
    data-license="CC-BY 4.0"
    data-source="Icomoon"
    {...props}>
    <g>
      <path d="M16 12c2.188 0 4 1.813 4 4s-1.813 4-4 4-4-1.813-4-4 1.813-4 4-4zM25.313 25.313v-5.313h2.688v5.313c0 1.438-1.25 2.688-2.688 2.688h-5.313v-2.688h5.313zM25.313 4c1.438 0 2.688 1.25 2.688 2.688v5.313h-2.688v-5.313h-5.313v-2.688h5.313zM6.688 6.688v5.313h-2.688v-5.313c0-1.438 1.25-2.688 2.688-2.688h5.313v2.688h-5.313zM6.688 20v5.313h5.313v2.688h-5.313c-1.438 0-2.688-1.25-2.688-2.688v-5.313h2.688z" />
    </g>
  </Icon>
);

export default FocalPoint;
