/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Folder = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 14 11" {...props}>
    <path d="M8.5 1.1h4.4A1.1 1.1 0 0 1 14 2.2v7.7a1.1 1.1 0 0 1-1.1 1.1H1.1a1 1 0 0 1-1-1.1.9.9 0 0 1-.1-.5V1.6A1.6 1.6 0 0 1 1.6 0H7a1.6 1.6 0 0 1 1.5 1.1" />
  </Icon>
);
export default Folder;
