/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const FormatList = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Material" viewBox="0 0 24 24" {...props}>
    <path d="M2 14h6v6H2M16 8h-6v2h6M2 10h6V4H2m8 0v2h12V4M10 20h6v-2h-6m0-2h12v-2H10" />
  </Icon>
);
export default FormatList;
