/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const H5P = (props: Props) => (
  <Icon viewBox="0 0 31 15" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="M0 14.7h.7V7.2h8v7.5h.7V0h-.7v6.6h-8V0H0v14.7zm16.5.3c2.1 0 4.3-1.7 4.3-4.7 0-3.2-1.9-4.5-4.2-4.5-1.1 0-1.9.3-2.6.8l.5-5.5H20V.4h-6.3l-.5 6.7.6.3c.8-.6 1.6-1 2.6-1 2.2 0 3.6 1.5 3.6 4 0 2.3-1.7 4-3.6 4-2 0-3-1-4-1.8l-.3.5c.8.9 2 1.9 4.3 1.9zm6-.3V0h3.4C29 0 31 1 31 4c0 2.8-1.8 4.2-5 4.2h-3v6.5h-.7zm.6-7.1h2.6c3 0 4.6-1 4.6-3.6S28.7.6 25.6.6h-2.5v7z" />
    </g>
  </Icon>
);

export default H5P;
