/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Heading3 = props => (
  <Icon
    viewBox="0 0 20.2 13.4"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M0,0H1.7V5.5H7.8V0H9.4V13.1H7.8V7H1.7v6.1H0Z" />
      <path d="M11.8,11.6l.8-1.1A4.5,4.5,0,0,0,15.9,12a2.3,2.3,0,0,0,2.6-2.3c0-1.6-1-2.6-4.1-2.6V5.9c2.7,0,3.6-1.1,3.6-2.4a2,2,0,0,0-2.2-2,3.9,3.9,0,0,0-2.7,1.3l-.9-1.1A5.5,5.5,0,0,1,15.9.1c2.2,0,3.8,1.2,3.8,3.3a3.1,3.1,0,0,1-2.3,3h0a3.3,3.3,0,0,1,2.8,3.2c0,2.3-1.9,3.7-4.2,3.7A5.4,5.4,0,0,1,11.8,11.6Z" />
    </g>
  </Icon>
);

export default Heading3;
