/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Heading4 = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="M0,0.2h1.9v6h6.6v-6h1.7v14.3H8.5V7.8H1.9v6.6H0V0.2z" />
      <path d="M18.9,14.5V2.7l-4.1,5.2h4.1v1.7l-4.2,0h-1.7V7.8l5.9-7.6l1.7,0l0,7.6h1.3v1.7h-1.3l0,4.9H18.9z" />
    </g>
  </Icon>
);

export default Heading4;
