/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Heading1 = props => (
  <Icon
    viewBox="0 0 20 13.1"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M0,0H1.7V5.5H7.8V0H9.4V13.1H7.8V7H1.7v6.1H0Z" />
      <path d="M12.8,11.8h2.9V2.4H13.4V1.3A7.7,7.7,0,0,0,16.1.4h1.3V11.8H20v1.3H12.8Z" />
    </g>
  </Icon>
);

export default Heading1;
