/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const ImageXxSmall = (props: Props) => (
  <Icon
    title="ImageXxSmall"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g>
      <path
        transform="translate(1.000000, 3.000000)"
        d="M20,12 L22,12 L22,14 L20,14 L20,12 L20,12 Z M20,8 L22,8 L22,10 L20,10 L20,8 L20,8 Z M22,16 L20,16 L20,18 C21,18 22,17 22,16 L22,16 Z M12,0 L14,0 L14,2 L12,2 L12,0 L12,0 Z M20,4 L22,4 L22,6 L20,6 L20,4 L20,4 Z M20,0 L20,2 L22,2 C22,1 21,0 20,0 L20,0 Z M0,4 L2,4 L2,6 L0,6 L0,4 L0,4 Z M0,8 L2,8 L2,10 L0,10 L0,8 L0,8 Z M16,0 L18,0 L18,2 L16,2 L16,0 L16,0 Z M16,16 L18,16 L18,18 L16,18 L16,16 L16,16 Z M12,16 L14,16 L14,18 L12,18 L12,16 L12,16 Z M8,16 L10,16 L10,18 L8,18 L8,16 L8,16 Z M2,0 C1,0 0,1 0,2 L2,2 L2,0 L2,0 Z M8,0 L10,0 L10,2 L8,2 L8,0 L8,0 Z M4,0 L6,0 L6,2 L4,2 L4,0 L4,0 Z M0,16 C2.22044605e-16,17.1045695 0.8954305,18 2,18 L6,18 L6,12 L0,12 L0,16 Z"
      />
    </g>
  </Icon>
);

export default ImageXxSmall;
