/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const InProgress = (props: Props) => (
  <Icon fill="none" data-license="Apache License 2.0" data-source="Knowit" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      d="M2.4 7h9.2v1.8H2.4zm0-1.6h9.2V3.7H2.4zm0 6.7h5.9v-1.7H2.4zM15 9.5l.5-.6c.4-.3.9-.3 1.2 0l.6.6c.3.3.3.8 0 1.2l-.6.5zm-.6.6-4.5 4.4v1.8h1.8l4.4-4.5z"
    />
  </Icon>
);
export default InProgress;
