/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const InProgress = (props: Props) => (
  <Icon viewBox="0 0 20 20" data-license="Apache License 2.0" data-source="Knowit" {...props}>
    <g>
      <path
        d="M2.44531 7.08333H11.612V8.75H2.44531V7.08333ZM2.44531 5.41667H11.612V3.75H2.44531V5.41667ZM2.44531 12.0833H8.27865V10.4167H2.44531V12.0833ZM14.9536 9.475L15.5453 8.88333C15.8703 8.55833 16.3953 8.55833 16.7203 8.88333L17.312 9.475C17.637 9.8 17.637 10.325 17.312 10.65L16.7203 11.2417L14.9536 9.475ZM14.362 10.0667L9.94531 14.4833V16.25H11.712L16.1286 11.8333L14.362 10.0667Z"
        fill="#444444"
      />
    </g>
  </Icon>
);

export default InProgress;
