/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Italic = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M10 4v3h2.2l-3.4 8H6v3h8v-3h-2.2l3.4-8H18V4z" />
  </Icon>
);
export default Italic;
