/**
 * Copyright (c) 2019-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Keyhole = props => (
  <Icon
    title="Keyhole"
    viewBox="0 0 24 24"
    data-license="CC-BY 4.0"
    data-source="Keyteq"
    {...props}>
    <g>
      <g transform="translate(2.000000, 2.000000)">
        <path
          d="M0,10 C2.22044605e-16,12.6521649 1.0535684,15.195704 2.92893219,17.0710678 C4.80429597,18.9464316 7.3478351,20 10,20 C15.5228475,20 20,15.5228475 20,10 C20,7.3478351 18.9464316,4.80429597 17.0710678,2.92893219 C15.195704,1.0535684 12.6521649,2.22044605e-16 10,0 C4.4771525,-1.77635684e-15 4.4408921e-16,4.4771525 0,10 L0,10 Z M2,10 C2,5.581722 5.581722,2 10,2 C12.1217319,2 14.1565632,2.84285472 15.6568542,4.34314575 C17.1571453,5.84343678 18,7.87826808 18,10 C18,14.418278 14.418278,18 10,18 C5.581722,18 2,14.418278 2,10 L2,10 Z"
          fillRule="nonzero"
        />
        <circle cx="10" cy="7.5" r="2.5" />
        <polygon points="9 9 11 9 12 15 8 15" />
      </g>
    </g>
  </Icon>
);

export default Keyhole;
