/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const LastUsed = (props: Props) => (
  <Icon viewBox="0 0 25.3 24" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="M13.5 0A11.8 11.8 0 0 0 3 6.5a1 1 0 0 0 .4 1.4 1.1 1.1 0 0 0 1.4-.5A9.8 9.8 0 0 1 13.5 2a9.9 9.9 0 0 1 9.8 10 9.9 9.9 0 0 1-9.8 10 9.7 9.7 0 0 1-8.8-5.7l3-1.3-6.1-3.1L0 18.5l2.8-1.3A12.1 12.1 0 0 0 13.5 24a12 12 0 0 0 0-24Z" />
      <path d="M12.8 5.1a.9.9 0 0 0-1 1v6.7a1.3 1.3 0 0 0 1.2 1.3h5a1.2 1.2 0 0 0 1.2-1.3 1.2 1.2 0 0 0-1.2-1.2h-4.2V6.1a.9.9 0 0 0-1-1Z" />
    </g>
  </Icon>
);

export default LastUsed;
