/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const LearningResource = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 47 55" {...props}>
    <path d="M45 55H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h43a2 2 0 0 1 2 2v51a2 2 0 0 1-2 2M2 2v51h43V2Z" />
    <path d="M39 25H8v-2h31Zm0-7H8v-2h31Zm0-7H8V9h31ZM21.8 45.7a4.6 4.6 0 0 1-1.6-.7l-1.5 1.2c-.1.1-.4.2-.5.1l-1.7-1.7c-.1-.1-.1-.3.1-.5l1.2-1.5a4.4 4.4 0 0 1-.6-1.6 10.7 10.7 0 0 1-1.8 0c-.2 0-.4-.1-.4-.3v-2.4c0-.2.2-.3.4-.3l1.9-.2a10.1 10.1 0 0 1 .7-1.5l-1.2-1.5a.4.4 0 0 1-.2-.5l1.7-1.7c.1-.1.3-.1.5.1a15.8 15.8 0 0 0 1.5 1.2l1.6-.7.1-1.8c0-.7.1-.4.3-.4h2.4c.2 0 .3.2.3.4l.2 1.9a7.6 7.6 0 0 1 1.6.6l1.5-1.2c.1-.1.4-.2.5-.1l1.7 1.7c.1.1.1.3-.1.5l-1.2 1.5a7.7 7.7 0 0 1 .7 1.6h1.7c.2 0 .4.1.4.3v2.4a.4.4 0 0 1-.4.3l-1.9.2a4.6 4.6 0 0 1-.7 1.6l1.2 1.5c.1.1.2.4.1.5l-1.7 1.7c-.1.1-.3.1-.5-.1l-1.5-1.2-1.6.7a13.7 13.7 0 0 1-.2 1.9c0 .2-.1.4-.3.4h-2.2a.9.9 0 0 1-.3-.6 11.1 11.1 0 0 0-.2-1.9m1.7-3.2a3 3 0 1 0-3-3 3 3 0 0 0 3 3" />
  </Icon>
);
export default LearningResource;
