/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon from '../Icon';

interface Props {
  children?: ReactNode;
}

const Learningpath = (props: Props) => (
  <Icon
    title="Learningpath"
    viewBox="0 0 59.8 50.8"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path
        d="M59.1,15,30.5.1h0a1.3,1.3,0,0,0-1.2,0L.7,15A1.4,1.4,0,0,0,0,16.1a1.3,1.3,0,0,0,1.3,1.3h5V36h-4A2.3,2.3,0,0,0,0,38.3V48.5a2.3,2.3,0,0,0,2.3,2.3H56.7A2.3,2.3,0,0,0,59,48.5V38.3A2.3,2.3,0,0,0,56.7,36H54.4V17.4h4.1a1.2,1.2,0,0,0,1.1-.7A1.2,1.2,0,0,0,59.1,15ZM8.3,17.4h7.2V36H8.3Zm34.9,0V36H36V17.4ZM33.9,36H26.7V17.4h7.2Zm-9.2,0H17.5V17.4h7.2Zm32,2a.3.3,0,0,1,.3.3V48.5a.3.3,0,0,1-.3.3H2.3a.3.3,0,0,1-.3-.3V38.3a.3.3,0,0,1,.3-.3H56.7Zm-4.3-2H45.2V17.4h7.2ZM4.2,15.4,29.9,2.1,55.6,15.4Z"
        transform="translate(0 0.1)"
      />
    </g>
  </Icon>
);

export default Learningpath;
