/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Learningpath = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 59.8 50.8" {...props}>
    <path d="M59.1 15.1 30.5.2a1.3 1.3 0 0 0-1.2 0L.7 15.1a1.4 1.4 0 0 0-.7 1.1 1.3 1.3 0 0 0 1.3 1.3h5v18.6h-4A2.3 2.3 0 0 0 0 38.4v10.2a2.3 2.3 0 0 0 2.3 2.3h54.4a2.3 2.3 0 0 0 2.3-2.3V38.4a2.3 2.3 0 0 0-2.3-2.3h-2.3V17.5h4.1a1.2 1.2 0 0 0 1.1-.7 1.2 1.2 0 0 0-.5-1.7M8.3 17.5h7.2v18.6H8.3Zm34.9 0v18.6H36V17.5Zm-9.3 18.6h-7.2V17.5h7.2Zm-9.2 0h-7.2V17.5h7.2Zm32 2a.3.3 0 0 1 .3.3v10.2a.3.3 0 0 1-.3.3H2.3a.3.3 0 0 1-.3-.3V38.4a.3.3 0 0 1 .3-.3zm-4.3-2h-7.2V17.5h7.2ZM4.2 15.5 29.9 2.2l25.7 13.3Z" />
  </Icon>
);
export default Learningpath;
