/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Link = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 21 20" {...props}>
    <path d="M14.94 5.83H11.6V7.5h3.34a2.5 2.5 0 0 1 2.5 2.5 2.5 2.5 0 0 1-2.5 2.5H11.6v1.67h3.34a4.17 4.17 0 0 0 0-8.34m-5 6.67H6.6A2.5 2.5 0 0 1 4.1 10a2.5 2.5 0 0 1 2.5-2.5h3.33V5.83H6.6a4.17 4.17 0 0 0 0 8.34h3.33zm-2.5-3.33h6.66v1.66H7.43z" />
  </Icon>
);
export default Link;
