/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const ListTwoColumns = props => (
  <Icon
    viewBox="0 0 48 48"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M6.5,21a3,3,0,0,0,0,6,3,3,0,0,0,0-6Zm0-12a3,3,0,0,0,0,6,3,3,0,0,0,0-6Zm0,24a3,3,0,0,0-3,3,3.1,3.1,0,0,0,3,3,3.1,3.1,0,0,0,3-3A3,3,0,0,0,6.5,33Zm5,5h10V34h-10Zm0-12h10V22h-10Zm0-16v4h10V10Z" />
      <path d="M28.5,21a3,3,0,1,0,3,3A2.9,2.9,0,0,0,28.5,21Zm0-12a3,3,0,1,0,3,3A2.9,2.9,0,0,0,28.5,9Zm0,24a3,3,0,0,0-3,3,3,3,0,0,0,6,0A3,3,0,0,0,28.5,33Zm5,5h11V34h-11Zm0-12h11V22h-11Zm0-16v4h11V10Z" />
    </g>
  </Icon>
);

export default ListTwoColumns;
