/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Media = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 60 44" {...props}>
    <path d="M59 0H1a1.1 1.1 0 0 0-1 1v42a1.1 1.1 0 0 0 1 1h58a1.1 1.1 0 0 0 1-1V1a1.1 1.1 0 0 0-1-1m-1 2v21.2L44.1 11.7 24.4 27.8l-15-8.4L2 25.7V2ZM2 42V28.3l7.6-6.5 15 8.4 19.5-15.9 13.7 11.3h.2V42Z" />
    <path d="M23.5 18a5.5 5.5 0 1 0-5.5-5.5 5.5 5.5 0 0 0 5.5 5.5m0-9a3.5 3.5 0 1 1-3.5 3.5A3.5 3.5 0 0 1 23.5 9" />
  </Icon>
);
export default Media;
