/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Media = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 21 20" {...props}>
    <path d="M18.08 2.5H3.07A1.8 1.8 0 0 0 1.4 4.17v11.66c0 .92.75 1.67 1.67 1.67h15a1.8 1.8 0 0 0 1.68-1.67V4.17a1.8 1.8 0 0 0-1.67-1.67m0 13.27-.07.06H3.07V4.23l.07-.06H18c.03.01.05.05.07.06zm-8.34-2.84-2.08-2.51-2.92 3.75H16.4l-3.75-5z" />
  </Icon>
);
export default Media;
