/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const PresentationPlay = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M2 3h8a2 2 0 0 1 2-2 2 2 0 0 1 2 2h8v2h-1v11h-5.8l1.8 6h-2l-1.8-6h-2.4L9 22H7l1.8-6H3V5H2V3m3 2v9h14V5H5m6.8 6.8-.3.2a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5c.1 0 .3 0 .3.2l1.4 1.3c.4.4.7.7.7 1 0 .3-.3.6-.7 1L12 11.8Z" />
    </g>
  </Icon>
);

export default PresentationPlay;
