/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const RelatedArticle = (props: Props) => (
  <Icon viewBox="0 0 48 56.9" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M0,46.9a9.8,9.8,0,0,0,9.6,10,9.8,9.8,0,0,0,9.6-10,10.2,10.2,0,0,0-4.5-8.5l3.7-7.8a16.9,16.9,0,0,0,5.6,1,16.9,16.9,0,0,0,5.6-1l3.7,7.8a10.2,10.2,0,0,0-4.5,8.5,9.8,9.8,0,0,0,9.6,10,10,10,0,0,0,0-20H36.9L33,28.7a15.7,15.7,0,1,0-18,0L11.1,37H9.6A9.8,9.8,0,0,0,0,46.9Z" />
    </g>
  </Icon>
);

export default RelatedArticle;
