/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const SearchFolder = props => (
  <Icon
    viewBox="0 0 59 44"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M41.3,32.5,30.2,24.4c.1-.4.3-.9.4-1.4a11.1,11.1,0,0,0-1.3-8.7A11.2,11.2,0,0,0,22.2,9,11.7,11.7,0,0,0,8.1,17.5a11.1,11.1,0,0,0,1.3,8.7,11.1,11.1,0,0,0,7.2,5.3,12.4,12.4,0,0,0,2.7.3,11.5,11.5,0,0,0,7.3-2.5l11.1,8Zm-12.7-10A9.5,9.5,0,1,1,10.1,18a9.5,9.5,0,0,1,9.3-7.2,9.3,9.3,0,0,1,2.3.2,9.5,9.5,0,0,1,6.9,11.5Zm-.5,5.4,1.2-1.6,9.2,6.6-1.2,1.7Z" />
      <path d="M57.6,44H1.2C.4,44,0,43.3,0,42.4V1.6A1.6,1.6,0,0,1,1.6,0h33a1.6,1.6,0,0,1,1.6,1.6V5.5H57.8A1.3,1.3,0,0,1,59,6.9V42.4A1.4,1.4,0,0,1,57.6,44ZM2,42H57V7.5H34.2V2H2Z" />
    </g>
  </Icon>
);

export default SearchFolder;
