/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const SearchMedia = props => (
  <Icon
    viewBox="0 0 52 40"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M51.2,0H.8A.9.9,0,0,0,0,.8V39.2a.9.9,0,0,0,.8.8H51.2a.9.9,0,0,0,.8-.8V.8A.9.9,0,0,0,51.2,0Zm-.7,1.5V18.7L38.6,9.8l-5.8,4.9a10.5,10.5,0,0,0-2.4-2.8,10,10,0,0,0-5.7-2.1,10.1,10.1,0,0,0-10.8,9.5v.3L8.7,16.4,1.5,22.5V1.5ZM32.6,25.4l7.2,5.4h0c.3.3.4.6.2.9l-.6.7a.5.5,0,0,1-.4.2h-.4l-7.3-5.4A7,7,0,0,0,32.6,25.4Zm-9.1,3a8.5,8.5,0,1,1,9-8A8.5,8.5,0,0,1,23.5,28.4ZM1.5,38.5v-14l7.3-6.2L14,21.4a10.2,10.2,0,0,0,3.7,6.5,10.2,10.2,0,0,0,12.3.3l7.5,5.7a2.5,2.5,0,0,0,1.7.4,2.1,2.1,0,0,0,1.6-.8l.5-.7a2.3,2.3,0,0,0-.4-3.3l-7.4-5.7a8.8,8.8,0,0,0,.7-3.2,11.2,11.2,0,0,0-.7-4.5l5.2-4.4,11.8,8.8v18Z" />
    </g>
  </Icon>
);

export default SearchMedia;
