/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const SearchTranslate = (props: Props) => (
  <Icon viewBox="0 0 58.5 41" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="m15.2 12.1.3-1.2 1-3.5h.1l.9 3.5.4 1.2Zm4.1 4.5h1.6L17.5 6.1h-1.9l-3.5 10.5h1.7l.8-3h3.8Z" />
      <path d="M57.1 7.5H32.6V1.6c0-1-.5-1.4-1.5-1.5H1.5C.6 0 .1.5.1 1.5v20.4a1.3 1.3 0 0 0 1.4 1.4h7v8.9c-.1.7.2 1.1.6 1.2h.4a1.4 1.4 0 0 0 1-.5l7.4-9.2.8-.5H26v5.9a1.4 1.4 0 0 0 .3 1.1c.3.4.7.4 1.2.4h12.2a1.9 1.9 0 0 1 .9.4l7.4 9.4a1.1 1.1 0 0 0 1 .6h.3a1.1 1.1 0 0 0 .7-1.2V31h7c1-.1 1.4-.6 1.5-1.6V9c0-1-.5-1.5-1.4-1.5ZM18.7 21.8a3.2 3.2 0 0 0-2.1 1l-6.7 8.1v-7.4a1.7 1.7 0 0 0-.5-1.2 1.8 1.8 0 0 0-1.2-.5H1.6V1.6H31v20.3Zm38.2 7.4h-6.7a2.1 2.1 0 0 0-1.3.5 1.6 1.6 0 0 0-.4 1.3v7.4L42 30.3a2.9 2.9 0 0 0-2.2-1.1H27.5v-5.8h3.3c1-.1 1.7-.6 1.7-1.5V9h24.4Zm-25.8-5.7Z" />
      <path d="M44 18.3a11.5 11.5 0 0 1-1.2 2.5l-.4.6a8.8 8.8 0 0 1-.2-2.8l1.7-.2Zm-3.8 1.2.6-.5c0 1.2.2 2.3.3 3.4a2 2 0 0 1-1.5.5c-.6 0-.8-.4-.8-1.1a2.7 2.7 0 0 1 1.4-2.3Zm6.7-1.6-1.2-.6a.9.9 0 0 1 .1-.5v-.2l-1.3-.3v.3a.9.9 0 0 1-.1.5 7.9 7.9 0 0 0-2.2.1l.1-1.1 5.6-.3h.1v-1.2h-5.5a5.2 5.2 0 0 1 .2-1.1v-.2l-1.4-.3v.2l-.3 1.5h-3.4v1.4H41l-.2 1.5a3.8 3.8 0 0 0-1.5.9 4 4 0 0 0-1.8 3.3 1.9 1.9 0 0 0 .6 1.7 1.8 1.8 0 0 0 1.5.7 5.2 5.2 0 0 0 4.3-2.7 11.1 11.1 0 0 0 1.4-2.9l.6.3a1.9 1.9 0 0 1 1.1 1.8 2.2 2.2 0 0 1-1 1.8 4.6 4.6 0 0 1-2.6 1h-.3l.5 1.2h.2a6.6 6.6 0 0 0 3.3-1.2 3.3 3.3 0 0 0 1.2-2.8 3.1 3.1 0 0 0-1.4-2.8Z" />
    </g>
  </Icon>
);

export default SearchTranslate;
