/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const SquareVideo = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 60 46" {...props}>
    <path d="M21.1 34.7a2 2 0 0 0 1.1.3 2.8 2.8 0 0 0 1.5-.4l17.9-9.5a2.3 2.3 0 0 0 0-4.2l-17.9-9.5a2.7 2.7 0 0 0-2.6-.1 2.4 2.4 0 0 0-1.1 2.2v19.1a2.4 2.4 0 0 0 1.1 2.1m.9-21.2a.6.6 0 0 1 .1-.4h.1a.6.6 0 0 1 .5.2l17.9 9.5a.4.4 0 0 1 .4.2.7.7 0 0 1-.4.3l-17.9 9.5a1 1 0 0 1-.6.2 1 1 0 0 1-.1-.4Z" />
    <path d="M58 0H2a2 2 0 0 0-2 2v42a2 2 0 0 0 2 2h56a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m0 44H2V2h56Z" />
  </Icon>
);
export default SquareVideo;
