/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const SquareVideo = (props: Props) => (
  <Icon viewBox="0 0 60 46" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path d="M21.1,34.7a2,2,0,0,0,1.1.3,2.8,2.8,0,0,0,1.5-.4l17.9-9.5a2.3,2.3,0,0,0,0-4.2L23.7,11.4a2.7,2.7,0,0,0-2.6-.1A2.4,2.4,0,0,0,20,13.5V32.6A2.4,2.4,0,0,0,21.1,34.7ZM22,13.5a.6.6,0,0,1,.1-.4h.1a.6.6,0,0,1,.5.2l17.9,9.5a.4.4,0,0,1,.4.2.7.7,0,0,1-.4.3L22.7,32.8a1,1,0,0,1-.6.2,1,1,0,0,1-.1-.4Z" />
      <path d="M58,0H2A2,2,0,0,0,0,2V44a2,2,0,0,0,2,2H58a2,2,0,0,0,2-2V2A2,2,0,0,0,58,0Zm0,44H2V2H58Z" />
    </g>
  </Icon>
);

export default SquareVideo;
