/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon from '../Icon';

interface Props {
  children?: ReactNode;
}

const SquareAudio = (props: Props) => (
  <Icon
    title="SquareAudio"
    viewBox="0 0 60 46"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path d="M58,0H2A2,2,0,0,0,0,2V44a2,2,0,0,0,2,2H58a2,2,0,0,0,2-2V2A2,2,0,0,0,58,0Zm0,44H2V2H58Z" />
      <path d="M34.2,33a1,1,0,0,0,1-1V15a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V32A1.1,1.1,0,0,0,34.2,33Z" />
      <path d="M38.5,39a.9.9,0,0,0,1-1V8a1,1,0,0,0-2,0V38A.9.9,0,0,0,38.5,39Z" />
      <path d="M47,30a1,1,0,0,0,1-1V19a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V29A1,1,0,0,0,47,30Z" />
      <path d="M42.8,33a1,1,0,0,0,1-1V15a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V32A1,1,0,0,0,42.8,33Z" />
      <path d="M30,30a1,1,0,0,0,1-1V19a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V29A1,1,0,0,0,30,30Z" />
      <path d="M17.2,33a1,1,0,0,0,1-1V15a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V32A1.1,1.1,0,0,0,17.2,33Z" />
      <path d="M25.8,33a1,1,0,0,0,1-1V15a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V32A1,1,0,0,0,25.8,33Z" />
      <path d="M13,30a1,1,0,0,0,1-1V19a.9.9,0,0,0-1-1,1,1,0,0,0-1,1V29A1,1,0,0,0,13,30Z" />
      <path d="M21.5,39a.9.9,0,0,0,1-1V8a1,1,0,0,0-2,0V38A.9.9,0,0,0,21.5,39Z" />
    </g>
  </Icon>
);

export default SquareAudio;
