/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const SquareAudio = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 60 46" {...props}>
    <path d="M58 0H2a2 2 0 0 0-2 2v42a2 2 0 0 0 2 2h56a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m0 44H2V2h56Z" />
    <path d="M34.2 33a1 1 0 0 0 1-1V15a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v17a1.1 1.1 0 0 0 1 1m4.3 6a.9.9 0 0 0 1-1V8a1 1 0 0 0-2 0v30a.9.9 0 0 0 1 1m8.5-9a1 1 0 0 0 1-1V19a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v10a1 1 0 0 0 1 1m-4.2 3a1 1 0 0 0 1-1V15a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v17a1 1 0 0 0 1 1M30 30a1 1 0 0 0 1-1V19a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v10a1 1 0 0 0 1 1m-12.8 3a1 1 0 0 0 1-1V15a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v17a1.1 1.1 0 0 0 1 1m8.6 0a1 1 0 0 0 1-1V15a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v17a1 1 0 0 0 1 1M13 30a1 1 0 0 0 1-1V19a.9.9 0 0 0-1-1 1 1 0 0 0-1 1v10a1 1 0 0 0 1 1m8.5 9a.9.9 0 0 0 1-1V8a1 1 0 0 0-2 0v30a.9.9 0 0 0 1 1" />
  </Icon>
);
export default SquareAudio;
