/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Subscript = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path fill="none" d="M0 0h24v24H0z" />
      <path d="M22 18h-2v1h3v1h-4v-2c0-.6.5-1 1-1h2v-1h-3v-1h3c.6 0 1 .5 1 1v1c0 .6-.4 1-1 1zM5.9 18h2.6l3.4-5.4h.2l3.4 5.4H18l-4.6-7.3L17.8 4h-2.7l-3 5h-.2L9 4H6.1l4.3 6.7L6 18z" />
    </g>
  </Icon>
);

export default Subscript;
