/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Superscript = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path fill="none" d="M0 0h24v24H0z" />
    <path d="M22 7h-2v1h3v1h-4V7c0-.6.5-1 1-1h2V5h-3V4h3c.6 0 1 .5 1 1v1c0 .5-.4 1-1 1M5.9 20h2.6l3.4-5.4h.2l3.4 5.4H18l-4.6-7.3L17.8 6h-2.7l-3 5h-.2L9 6H6.1l4.3 6.7L6 20z" />
  </Icon>
);
export default Superscript;
