/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Table = (props: Props) => (
  <Icon viewBox="0 0 32 32" data-license="CC-BY 4.0" data-source="Icomoon" {...props}>
    <g>
      <path d="M0 6v22h32V6H0zm12 14v-4h8v4h-8zm8 2v4h-8v-4h8zm0-12v4h-8v-4h8zm-10 0v4H2v-4h8zm-8 6h8v4H2v-4zm20 0h8v4h-8v-4zm0-2v-4h8v4h-8zM2 22h8v4H2v-4zm20 4v-4h8v4h-8z" />
    </g>
  </Icon>
);

export default Table;
