/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Taxonomy = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 60 44" {...props}>
    <path d="M58 29h-5v-5a2.9 2.9 0 0 0-3-3H31.5v-6H36a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H24a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h5.5v6H10a2.9 2.9 0 0 0-3 3v5H2a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V31a2 2 0 0 0-2-2H9v-5a.9.9 0 0 1 1-1h19.5v6H24a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V31a2 2 0 0 0-2-2h-4.5v-6H50a.9.9 0 0 1 1 1v5h-5a2 2 0 0 0-2 2v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V31a2 2 0 0 0-2-2M24 2h12v11H24ZM14 42H2V31h12Zm22-11v11H24V31zm22 11H46V31h12Z" />
  </Icon>
);
export default Taxonomy;
