/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const TopicArticle = props => (
  <Icon
    viewBox="0 0 47 55"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path
        class="cls-1"
        d="M45,0H2A2,2,0,0,0,0,2V53a2,2,0,0,0,2,2H45a2,2,0,0,0,2-2V2A2,2,0,0,0,45,0Zm0,53H2V2H45Z"
      />
      <rect class="cls-1" x="8.8" y="34.1" width="29.5" height="2" />
      <rect class="cls-1" x="8.8" y="41.6" width="22.2" height="2" />
      <rect class="cls-1" x="8.8" y="26.5" width="29.5" height="2" />
      <path class="cls-1" d="M38.5,8.6H8.5V20h30Zm-2,9.4h-26V10.6h26Z" />
    </g>
  </Icon>
);

export default TopicArticle;
