/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const TopicArticle = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 47 55" {...props}>
    <path d="M45 0H2a2 2 0 0 0-2 2v51a2 2 0 0 0 2 2h43a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m0 53H2V2h43Z" />
    <path d="M8.8 34.1h29.5v2H8.8zm0 7.5H31v2H8.8zm0-15.1h29.5v2H8.8zM38.5 8.6h-30V20h30Zm-2 9.4h-26v-7.4h26Z" />
  </Icon>
);
export default TopicArticle;
