/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Video = (props: Props) => (
  <Icon viewBox="0 0 32 32" data-license="CC-BY 4.0" data-source="Knowit" {...props}>
    <g>
      <path fill="none" stroke="#444" d="M31 16 1 31V1z" />
    </g>
  </Icon>
);

export default Video;
