/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Video = props => (
  <Icon
    viewBox="0 0 19 20"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path
        fill="none"
        stroke="#343434"
        stroke-width="1.5"
        d="M0,10.943587 L0,7.05561494 L0,1.20032907 C0,0.130164764 0.763501216,-0.306260096 1.69536424,0.228336058 L6.8029916,3.155979 C7.73485463,3.69057515 9.26087821,4.56536886 10.1937201,5.09996501 L15.3003686,8.02760795 C16.2332105,8.5622041 16.2332105,9.43699781 15.3003686,9.97159396 L10.1937201,12.8992369 C9.26087821,13.434805 7.73485463,14.3086268 6.8029916,14.8432229 L1.69536424,17.7718378 C0.763501216,18.306434 0,17.8690371 0,16.7998448 L0,10.943587 Z"
        transform="translate(1.444 1)"
      />
    </g>
  </Icon>
);

export default Video;
