/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Video = props => (
  <Icon
    viewBox="0 0 32 32"
    data-license="CC-BY 4.0"
    data-source="Knowit"
    {...props}>
    <g>
      <path fill="none" stroke="#444" d="M31.06 16L.942 31.06V.94z" />
    </g>
  </Icon>
);

export default Video;
