/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { readFile, readdir, stat, writeFile } from "fs/promises";
import { join, dirname } from "path";
import { optimize } from "svgo";

const __dirname = dirname(new URL(import.meta.url).pathname);
const rootDir = join(__dirname, "..", "packages", "icons");
const today = new Date(new Date().setHours(0, 0, 0, 0));

const copyright = await readFile(join(__dirname, "..", "COPYRIGHT"), "utf-8");

const autoNotice = `// N.B! AUTOGENERATED FILE. DO NOT EDIT`;
const imports = `import type { JSX } from "react";\nimport { Icon, type Props } from "../Icon";`;
const regexPattern = /(\d{4})-/g; // This finds the year so we can replace it with current year in the .tsx file

const allFileNames = await readdir(`${rootDir}/svg`);
const svgFiles = allFileNames.filter((file) => file.endsWith(".svg"));
const allFiles = await Promise.all(
  svgFiles.map(async (filename) => {
    const filePath = `${rootDir}/svg/${filename}`;
    const { ctime, mtime } = await stat(filePath);
    const file = await readFile(filePath, "utf8");
    return { filename, file, ctime, mtime };
  }),
);

const filePromises = allFiles.map(async ({ filename, file, ctime, mtime }) => {
  // if (mtime && mtime < today) return;
  const componentName = filename.split(".")[0];
  const optimizedSvg = optimize(file, {
    multipass: true,
    plugins: [
      {
        name: "cleanupListOfValues",
        params: { overrides: { floatPrecision: 2 } },
      },
      {
        name: "preset-default",
        params: {
          overrides: {
            cleanupNumericValues: { floatPrecision: 2 },
            convertPathData: { floatPrecision: 2 },
            convertTransform: { floatPrecision: 2 },
          },
        },
      },
      "mergePaths",
      "removeXMLNS",
    ],
  });

  const component = optimizedSvg.data.replace(/^<svg([^>]*)>/, "<Icon$1 {...props}>").replace("</svg>", "</Icon>");

  const componentContent = `${copyright.replace(regexPattern, `${ctime.getFullYear()}-`)}
${autoNotice}
${imports}
export const ${componentName} = (props: Props): JSX.Element => (
  ${component}
);`;
  await writeFile(`${rootDir}/src/icons/${componentName}.tsx`, componentContent);
});

const exports = svgFiles.map((icon) => `export { ${icon.split(".")[0]} } from "./${icon.split(".")[0]}";`).join("\n");
const file = `${copyright}\n${autoNotice}\n${exports}\n`;
await writeFile(`${rootDir}/src/icons/index.ts`, file);

await Promise.all(filePromises);
