/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { mkdir, readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { isTag, isText, type ChildNode, type Element } from "domhandler";
import { attributesToProps } from "html-react-parser";
import { parseDocument } from "htmlparser2";
import { format } from "oxfmt";
import { optimize, type Config } from "svgo";

const __dirname = dirname(new URL(import.meta.url).pathname);
const rootDir = join(__dirname, "..", "packages", "icons");
const svgDir = join(rootDir, "svg");
const today = new Date(new Date().setHours(0, 0, 0, 0));
const shouldGenerateAll = process.argv.includes("--all");
const outDirArg = process.argv.find((arg) => arg.startsWith("--out-dir="));
const outputDir = outDirArg
  ? resolve(process.cwd(), outDirArg.slice("--out-dir=".length))
  : join(rootDir, "src", "icons");

const svgoConfig: Config = {
  multipass: true,
  plugins: [
    {
      name: "cleanupListOfValues",
      params: {
        overrides: {
          floatPrecision: 2,
        },
      },
    },
    {
      name: "preset-default",
      params: {
        overrides: {
          cleanupNumericValues: { floatPrecision: 2 },
          convertPathData: { floatPrecision: 2 },
          convertTransform: { floatPrecision: 2 },
        },
      },
    },
    "mergePaths",
    "removeXMLNS",
  ] as NonNullable<Parameters<typeof optimize>[1]>["plugins"],
};

const copyright = await readFile(join(__dirname, "..", "COPYRIGHT"), "utf-8");

const autoNotice = `// N.B! AUTOGENERATED FILE. DO NOT EDIT`;
const imports = `import type { JSX } from 'react'; import { Icon, type Props } from '../Icon';`;
const yearPattern = /(\d{4})-/g;

const stringifyAttributes = (attrs: Record<string, string>) => {
  const entries = Object.entries(attributesToProps(attrs));
  return entries.map(([name, val]) => ` ${name}="${String(val)}"`).join("");
};

const stringifyNode = (node: ChildNode): string => {
  if (isText(node)) {
    return node.data.trim();
  }

  if (!isTag(node)) {
    return "";
  }

  const openTag = `<${node.name}${stringifyAttributes(node.attribs)}`;
  const children = node.children.map(stringifyNode).filter(Boolean);

  if (!children.length) {
    return `${openTag} />`;
  }

  return `${openTag}>\n${children.join("\n")}\n</${node.name}>`;
};

const getSvgElement = (svg: string): Element => {
  const svgElement = parseDocument(svg, { xmlMode: true }).children[0];
  if (isTag(svgElement) && svgElement.name === "svg") {
    return svgElement;
  }
  throw new Error("SVG root element not found");
};

const toIconJsx = (svgElement: Element): string => {
  const { xmlns, "data-license": _, "data-source": __, ...attributes } = svgElement.attribs;
  const iconAttributes = stringifyAttributes(attributes);
  const children = svgElement.children.map(stringifyNode).filter(Boolean).join("\n");

  return children ? `<Icon${iconAttributes} {...props}>\n${children}\n</Icon>` : `<Icon${iconAttributes} {...props} />`;
};

const renderComponent = (componentName: string, ctime: Date, jsx: string, license: string, source: string): string => {
  return `${copyright.replace(yearPattern, `${ctime.getFullYear()}-`)}

${autoNotice}
// Source: ${source}
// License: ${license}
${imports}
export const ${componentName} = (props: Props): JSX.Element => (
  ${jsx}
);
`;
};

await mkdir(outputDir, { recursive: true });

const svgFiles = (await readdir(svgDir)).filter((file) => file.endsWith(".svg"));

const filePromises = svgFiles.map(async (filename) => {
  const filePath = join(svgDir, filename);
  const { ctime, mtime } = await stat(filePath);
  if (!shouldGenerateAll && mtime && mtime < today) return;

  const file = await readFile(filePath, "utf8");
  const componentName = filename.slice(0, -4);
  const optimized = optimize(file, svgoConfig);
  const svgElement = getSvgElement(optimized.data);
  const { "data-license": license, "data-source": source } = svgElement.attribs;

  if (!license || !source) {
    throw new Error(`${filename} is missing ${!license ? "data-license" : "data-source"}`);
  }

  const jsx = toIconJsx(svgElement);
  const fileName = join(outputDir, `${componentName}.tsx`);
  const component = renderComponent(componentName, ctime, jsx, license, source);
  const formattedComponent = await format(fileName, component);
  await writeFile(fileName, formattedComponent.code);
});

const exports = svgFiles
  .map((filename) => {
    const componentName = filename.slice(0, -4);
    return `export { ${componentName} } from "./${componentName}";`;
  })
  .join("\n");
const indexFile = `${copyright}\n${autoNotice}\n${exports}\n`;
await writeFile(join(outputDir, "index.ts"), indexFile);

await Promise.all(filePromises);
