/**
 * Copyright (c) 2016-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

import { transform } from "@svgr/core";
import { readFile, readdir, stat, writeFile } from "fs/promises";
import { format } from "oxfmt";
import { join, dirname } from "path";

const __dirname = dirname(new URL(import.meta.url).pathname);
const rootDir = join(__dirname, "..", "packages", "icons");
const today = new Date(new Date().setHours(0, 0, 0, 0));

const copyright = await readFile(join(__dirname, "..", "COPYRIGHT"), "utf-8");

const autoNotice = `// N.B! AUTOGENERATED FILE. DO NOT EDIT`;
const imports = `import type { JSX } from 'react'; import { Icon, type Props } from '../Icon';`;

const allFileNames = await readdir(`${rootDir}/svg`);
const svgFiles = allFileNames.filter((file) => file.endsWith(".svg"));
const allFiles = await Promise.all(
  svgFiles.map(async (filename) => {
    const filePath = `${rootDir}/svg/${filename}`;
    const { ctime, mtime } = await stat(filePath);
    const file = await readFile(filePath, "utf8");
    return { filename, file, ctime, mtime };
  }),
);
const filePromises = allFiles.map(async ({ filename, file, ctime, mtime }) => {
  if (mtime && mtime < today) return;
  const componentName = filename.split(".")[0];
  const regexPattern = /(\d{4})-/g; // This finds the year so we can replace it with current year in the .tsx file
  const component = await transform(
    file,
    {
      jsxRuntime: "automatic",
      typescript: true,
      plugins: ["@svgr/plugin-svgo", "@svgr/plugin-jsx"],
      svgo: true,
      svgoConfig: {
        multipass: true,
        plugins: [
          {
            name: "cleanupListOfValues",
            params: {
              overrides: {
                floatPrecision: 2,
              },
            },
          },
          {
            name: "preset-default",
            params: {
              overrides: {
                cleanupNumericValues: { floatPrecision: 2 },
                convertPathData: { floatPrecision: 2 },
                convertTransform: { floatPrecision: 2 },
              },
            },
          },
          "mergePaths",
          "removeXMLNS",
        ],
      },
      template: (variables, { tpl }) => {
        return tpl`
            ${copyright.replace(regexPattern, `${ctime.getFullYear()}-`) + "\u000A"}

            ${autoNotice}

            ${imports}


            ${variables.interfaces};

            export const ${variables.componentName} = (props: Props): JSX.Element => (
              ${variables.jsx}
            );
            `;
      },
    },
    { componentName, filePath: `${rootDir}/src/icons/${componentName}.tsx` },
  );

  const fileName = `${rootDir}/src/icons/${componentName}.tsx`;
  const componentWithIcon = component.replace("<svg", "<Icon").replace("</svg>", "</Icon>");
  const formattedComponent = await format(fileName, componentWithIcon);
  await writeFile(fileName, formattedComponent.code);
});

const exports = svgFiles.map((icon) => `export { ${icon.split(".")[0]} } from "./${icon.split(".")[0]}";`).join("\n");
const file = `${copyright}\n${autoNotice}\n${exports}\n`;
await writeFile(`${rootDir}/src/icons/index.ts`, file);

await Promise.all(filePromises);
