/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const LearningPathRead = (props: Props) => (
  <Icon
    title="LearningPathRead"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Keyteq"
    {...props}>
    <g>
      <path d="M9,20.42L2.79,14.21L5.62,11.38L9,14.77L18.88,4.88L21.71,7.71L9,20.42Z" />
    </g>
  </Icon>
);

export default LearningPathRead;
