/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const LearningPathArticle = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Keyteq" viewBox="0 0 24 24" {...props}>
    <path d="M3 6h18v2H3zm0 5h18v2H3zm0 5h12v2H3z" />
  </Icon>
);
export default LearningPathArticle;
