/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const LearningPathRead = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Keyteq" {...props}>
    <g>
      <path d="m9 20.4-6.2-6.2 2.8-2.8L9 14.8l9.9-10 2.8 3L9 20.3Z" />
    </g>
  </Icon>
);

export default LearningPathRead;
