/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const LearningPathQuiz = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M10 19h3v3h-3v-3m2-17c5.4.2 7.7 5.6 4.5 9.7-.8 1-2.2 1.6-2.8 2.5C13 15 13 16 13 17h-3c0-1.7 0-3 .7-4 .6-1 2-1.7 2.8-2.3C15.9 8.4 15.3 5.3 12 5a3 3 0 0 0-3 3H6a6 6 0 0 1 6-6Z" />
    </g>
  </Icon>
);

export default LearningPathQuiz;
