/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const LearningPath = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M4 19h6v-2H4zM20 5H4v2h16zm-3 6H4v2h13.3c1 0 2 .9 2 2s-1 2-2 2H15v-2l-3 3 3 3v-2h2a4 4 0 1 0 0-8" />
    <path fill="none" d="M0 0h24v24H0z" />
  </Icon>
);
export default LearningPath;
