/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const QuestionMark = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M12 19a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m0-17a6 6 0 0 1 6 6c0 2.16-.75 3.3-2.67 4.92C13.4 14.56 13 15.3 13 17h-2c0-2.47.79-3.7 3.03-5.6C15.55 10.1 16 9.43 16 8a4 4 0 0 0-8 0v1H6V8a6 6 0 0 1 6-6" />
  </Icon>
);
export default QuestionMark;
