/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const SharedResource = props => (
  <Icon
    title="SharedResource"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Keyteq"
    {...props}>
    <g>
      <title>Delte ressurser</title>
      <g stroke="none" fill="none" strokeWidth="1" fillRule="evenodd">
        <g>
          <g>
            <polygon points="0 0 24 0 24 24 0 24" />
            <path
              d="M6,17 L9,17 L11,13 L11,7 L5,7 L5,13 L8,13 L6,17 Z M14,17 L17,17 L19,13 L19,7 L13,7 L13,13 L16,13 L14,17 Z"
              fill="currentColor"
              fillRule="nonzero"
            />
          </g>
        </g>
      </g>
    </g>
  </Icon>
);

export default SharedResource;
