/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Subject = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M18.3 19.4V3.7H5.8v15.7l6.2-2.7zM17.7 2c.7 0 1.2.2 1.6.7.5.4.7 1 .7 1.5V22l-8-3.3L4 22V4.2c0-.6.2-1 .7-1.5A2 2 0 0 1 6.3 2z"
    />
  </Icon>
);
export default Subject;
