/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const TasksAndActivities = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <g fill="none" fillRule="evenodd">
        <path d="M0 0h24v24H0z" />
        <path
          fill="currentColor"
          d="M17.8 8 14 4.2l-10 10V18h3.8l10-10Zm3-3c.3-.3.3-1 0-1.4l-2.4-2.3a1 1 0 0 0-1.4 0l-2 2L18.8 7l2-2ZM0 22h24v2H0z"
          fillRule="nonzero"
        />
      </g>
    </g>
  </Icon>
);

export default TasksAndActivities;
