/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const TasksAndActivities = props => (
  <Icon
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g>
      <title>Oppgaver og aktiviteter</title>
      <g
        id="Page-1"
        stroke="none"
        fill="none"
        strokeWidth="1"
        fillRule="evenodd">
        <g id="oppgaver-og-aktiviteter">
          <g id="Shape">
            <polygon points="0 0 24 0 24 24 0 24" />
            <path
              d="M17.75,8 L14,4.25 L4,14.25 L4,18 L7.75,18 L17.75,8 Z M20.71,5.04 C21.1,4.65 21.1,4.02 20.71,3.63 L18.37,1.29 C17.98,0.9 17.35,0.9 16.96,1.29 L15,3.25 L18.75,7 L20.71,5.04 Z"
              fill="currentColor"
              fillRule="nonzero"
            />
            <polygon
              fill="currentColor"
              points="0 22 24 22 24 24 0 24"
              fillRule="nonzero"
            />
          </g>
        </g>
      </g>
    </g>
  </Icon>
);

export default TasksAndActivities;
