/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const TasksAndActivities = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <g fill="none" fillRule="evenodd">
      <path d="M0 0h24v24H0z" />
      <path
        fill="currentColor"
        fillRule="nonzero"
        d="M17.8 8 14 4.2l-10 10V18h3.8zm3-3c.3-.3.3-1 0-1.4l-2.4-2.3a1 1 0 0 0-1.4 0l-2 2L18.8 7zM0 22h24v2H0z"
      />
    </g>
  </Icon>
);
export default TasksAndActivities;
