/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Additional = (props: Props) => (
  <Icon viewBox="0 0 23 23" data-license="CC-BY 4.0" data-source="Keyteq" {...props}>
    <g>
      <g fill="none" transform="translate(1.000000, 1.000000)">
        <circle cx="10.5" cy="10.5" r="10.5" stroke="#184673" />
        <path fill="#184673" d="M9.3 8.9H7V7h6.9v1.9h-2.3v6.8H9.3z" />
      </g>
    </g>
  </Icon>
);

export default Additional;
