/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Additional = props => (
  <Icon
    title="Additional"
    viewBox="0 0 50 50"
    data-license="CC-BY 4.0"
    data-source="Netlife"
    {...props}>
    <circle fill="#CEDDE9" cx="25" cy="25" r="24.7" />
    <g>
      <path
        fill="#21588F"
        className="st1"
        d="M22.5,21.1h-5V17h15v4.2h-5v14.7h-5V21.1z"
      />
    </g>
  </Icon>
);

export default Additional;
