/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Additional = (props: Props) => (
  <Icon
    title="Additional"
    viewBox="0 0 23 23"
    data-license="CC-BY 4.0"
    data-source="Keyteq"
    {...props}>
    <g>
      <title>Tilleggstoff</title>
      <g stroke="none" fill="none" strokeWidth="1" fillRule="evenodd">
        <g transform="translate(1.000000, 1.000000)" fillRule="nonzero">
          <circle stroke="#184673" cx="10.5" cy="10.5" r="10.5" />
          <polygon
            fill="#184673"
            points="9.3 8.886 7 8.886 7 7 13.9 7 13.9 8.932 11.6 8.932 11.6 15.694 9.3 15.694"
          />
        </g>
      </g>
    </g>
  </Icon>
);

export default Additional;
