/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Announcement = (props: Props) => (
  <Icon viewBox="0 0 22 18" data-license="CC-BY 4.0" data-source="Bouvet" {...props}>
    <g>
      <path d="M17.77 9.812V8.187h4.063v1.625h-4.062Zm1.355 7.855-3.277-2.438.975-1.3 3.277 2.438-.975 1.3Zm-2.22-13.623-.976-1.3 3.196-2.41.975 1.3-3.196 2.41ZM3.687 16.584V12.25H1.792c-.447 0-.83-.16-1.148-.477a1.565 1.565 0 0 1-.477-1.148v-3.25c0-.447.159-.83.477-1.148.318-.318.7-.477 1.148-.477h4.875l5.416-3.25v13l-5.416-3.25H5.313v4.333H3.688Zm9.479-3.955V5.371c.487.433.88.961 1.178 1.584.298.623.447 1.305.447 2.045s-.15 1.422-.447 2.045a4.947 4.947 0 0 1-1.178 1.584ZM1.792 7.375v3.25H7.1l3.358 2.004V5.371L7.1 7.375H1.792Z" />
    </g>
  </Icon>
);

export default Announcement;
