/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Announcement = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Bouvet" viewBox="0 0 22 18" {...props}>
    <path d="M17.8 9.8V8.2h4v1.6zm1.3 7.9-3.3-2.5 1-1.3 3.3 2.5zM17 4l-1-1.3L19.1.3l1 1.3L16.9 4ZM3.7 16.6v-4.4h-2c-.4 0-.7-.1-1-.4a1.6 1.6 0 0 1-.5-1.2V7.4c0-.5.1-.9.4-1.2.4-.3.7-.4 1.2-.4h4.9L12 2.5v13l-5.4-3.3H5.3v4.4zm9.5-4V5.4A5 5 0 0 1 14.8 9c0 .7-.2 1.4-.5 2a5 5 0 0 1-1.1 1.6M1.8 7.4v3.2H7l3.4 2V5.4L7 7.4z" />
  </Icon>
);
export default Announcement;
