/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const ArrowDropDownRounded = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path fill="none" d="M0 0h24v24H0z" />
    <path d="m8.7 11.7 2.6 2.6c.4.4 1 .4 1.4 0l2.6-2.6a1 1 0 0 0-.7-1.7H9.4a1 1 0 0 0-.7 1.7" />
  </Icon>
);
export default ArrowDropDownRounded;
