/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const ArrowCollapse = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M19.5 3 15 7.7V4h-2v7h7V9h-3.6L21 4.5l-1.4-1.4M4 13v2h3.6L3 19.5l1.4 1.4L9 16.4V20h2v-7H4Z" />
    </g>
  </Icon>
);

export default ArrowCollapse;
