/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Audio = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 25 25" {...props}>
    <path d="M8.46 18.88a1 1 0 0 0 1-1v-10c0-.55-.45-1-1-1s-1 .45-1 1v10a1 1 0 0 0 1 1m4 4a1 1 0 0 0 1-1v-18c0-.55-.45-1-1-1s-1 .45-1 1v18a1 1 0 0 0 1 1m-8-8a1 1 0 0 0 1-1v-2c0-.56-.45-1-1-1s-1 .44-1 1v2a1 1 0 0 0 1 1m12 4a1 1 0 0 0 1-1v-10c0-.55-.45-1-1-1s-1 .45-1 1v10a1 1 0 0 0 1 1m3-7v2c0 .54.45 1 1 1s1-.46 1-1v-2c0-.56-.45-1-1-1s-1 .44-1 1" />
  </Icon>
);
export default Audio;
