/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Audiobook = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="SIL Open Font License 1.1" data-source="Material Community Icons" {...props}>
    <g>
      <path d="M18 22H6a2 2 0 0 1-2-2V4c0-1.1.9-2 2-2h1v7l2.5-1.5L12 9V2h6a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2m-5-7a2 2 0 0 0-2 2 2 2 0 0 0 2 2 2 2 0 0 0 2-2v-5h3v-2h-4v5.3a2 2 0 0 0-1-.3Z" />
    </g>
  </Icon>
);

export default Audiobook;
