/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Audio = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Knowit" viewBox="0 0 34 21" {...props}>
    <path
      fill="none"
      stroke="#444"
      d="M32.5 8c.3 0 .5.2.5.5v3.3a.5.5 0 1 1-1 0V8.5c0-.3.2-.5.5-.5zM17 8c.3 0 .5.2.5.5v3.3a.5.5 0 1 1-1 0V8.5c0-.3.2-.5.5-.5zm-3.9-3c.3 0 .5.2.5.5v8.7a.5.5 0 0 1-1 0V5.5c0-.3.3-.5.5-.5zM9.2 1c.3 0 .5.2.5.5v18a.5.5 0 0 1-1 0v-18c0-.3.3-.5.5-.5zM21 5c.2 0 .5.2.5.5v8.7a.5.5 0 0 1-1 0V5.5c0-.3.2-.5.5-.5zm3.9-4c.2 0 .4.2.4.5v18a.5.5 0 0 1-1 0v-18c0-.3.3-.5.6-.5zm3.8 4c.3 0 .5.2.5.5v8.7a.5.5 0 1 1-1 0V5.5c0-.3.3-.5.5-.5zM1.5 8c.3 0 .5.2.5.5v3.3a.5.5 0 1 1-1 0V8.5c0-.3.2-.5.5-.5zm3.9-3c.2 0 .4.2.4.5v8.7a.5.5 0 0 1-1 0V5.5c0-.3.3-.5.6-.5z"
    />
  </Icon>
);
export default Audio;
