/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const AudioDocument = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Keyteq" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="m14 2 6 6v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4c0-1.1.9-2 2-2zm4 18V9h-5V4H6v16zm-5-9c1.8.4 3.1 1.8 3.1 3.6 0 1.7-1.3 3.2-3.1 3.5v-.8a2.9 2.9 0 0 0 2.2-2.7c0-1.3-1-2.4-2.2-2.8zm1.1 3.8a2 2 0 0 1-1.1 1.8V13a2 2 0 0 1 1.1 1.8M8 13.2h1.8L12 11v7.1L9.8 16H8v-2.7Z"
    />
  </Icon>
);
export default AudioDocument;
