/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Bell = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 16 20" {...props}>
    <path d="M0 17v-2h2V8c0-1.4.4-2.6 1.3-3.7.8-1 1.9-1.8 3.2-2.1v-.7c0-.4.1-.8.4-1C7.2 0 7.6 0 8 0c.4 0 .8.1 1 .4.4.3.5.7.5 1.1v.7A5.9 5.9 0 0 1 14 8v7h2v2zm8 3a2 2 0 0 1-1.4-.6A2 2 0 0 1 6 18h4c0 .6-.2 1-.6 1.4A2 2 0 0 1 8 20" />
  </Icon>
);
export default Bell;
