/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const BlobPointy = (props: Props) => (
  <Icon viewBox="0 0 165 180" data-license="NDLA" data-source="NDLA" {...props}>
    <g>
      <path d="M98.7 178.3c-9 1.6-18.1 3.4-26-1.3A70.6 70.6 0 0 1 53 157c-5.7-7.9-11.1-16.1-17.9-22.7-6-5.8-13.1-10-19.4-15.4A42.7 42.7 0 0 1 1 98.1a42.2 42.2 0 0 1 3.7-28.5C8.9 60.9 15 53.8 20.9 46.7l10.4-12.2C43.1 20.7 55.6 6.3 71.8 1.6a47.5 47.5 0 0 1 35.4 4.7c5 2.7 9.7 5.9 14.1 9.5 14 11 27.1 24.5 35.4 41.6a77 77 0 0 1 5 56.8A101 101 0 0 1 146 141c-12.7 17.3-28 34.6-47.4 37.3" />
    </g>
  </Icon>
);

export default BlobPointy;
