/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const BlobPointy = (props: Props) => (
  <Icon viewBox="0 0 165 180" data-license="NDLA" data-source="NDLA" {...props}>
    <g>
      <path d="M98.7034 178.298C89.7451 179.862 80.6032 181.68 72.7374 177.038C64.8716 172.397 58.6488 164.769 52.9592 156.938C47.2696 149.108 41.8946 140.86 35.0951 134.33C29.0471 128.53 21.9853 124.264 15.6839 118.922C9.38254 113.58 3.44822 106.785 1.10595 98.0804C-1.42858 88.6448 0.64277 78.1935 4.78544 69.5603C8.92811 60.9272 14.9761 53.7667 20.9453 46.7281L31.3457 34.4791C43.0571 20.6863 55.6249 6.30462 71.811 1.61222C83.5573 -1.80042 96.2213 0.413583 107.233 6.28414C112.15 8.99894 116.866 12.1822 121.331 15.8011C135.314 26.8312 148.424 40.2584 156.674 57.4435C164.925 74.6286 167.914 95.9474 161.63 114.209C158.178 124.244 152.2 132.806 146.134 141.003C133.374 158.269 118.167 175.647 98.7034 178.328" />
    </g>
  </Icon>
);

export default BlobPointy;
