/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const BlocksLight = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Labs." viewBox="0 0 243 282" {...props}>
    <g fill="none" fillRule="evenodd">
      <path fill="#E7D2FC" d="m121.4 2.8 119.1 68.5v69.8l-59.2 34.1-59.9-34.1V71.6L62.3 37.9z" />
      <path d="M180.2 173.7v-67.3M62.3 173.9l58-33.5V72.8l-58 33.5zm60-33.3v.1h.1zm56.5 34.6-57.4-33.1-57.3 33.1 57.3 33.1zm3.4-68.8v66.9l57.1-33V73.4zm-120.9-1.8 57.8-33.4-57.3-33.1L4 71.5zm178 105.7v-67.7l-117 67.5v67.7zm-179-104L3.4 73.5v136.8l56.9 32.8zm60 103.7-58-33.5v67.8l58 33.4z" />
      <path
        fill="#FFF"
        fillRule="nonzero"
        d="m121.9.5-.5-.3L.9 69.8l-.5.3v142l120.4 69.4.5.3 120.5-69.5.5-.3V70zm-2.6 210.1v65.5l-56-32.3v-65.5zm-2.1-139.4-55.9 32.2L6 71.5l55.8-32.2zm63.9 32.3L65.8 36.9l55.6-32 115.3 66.5zm57.2 40.9v65.4l-115 66.2v-65.3zm-117-1.1 55.4 31.9-55.3 31.9L66 175.2zm57.9-36.3v65l-55.9-32.2v-65zm-59.9-32.5v65.3l-56 32.3v-65.3zm63.9 97.1V107l55.1-31.8v64.6zM59.3 106.9v134.5L4.4 209.8V75.2z"
      />
    </g>
  </Icon>
);
export default BlocksLight;
