/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon from '../Icon';

interface Props {
  children?: ReactNode;
}

const BlocksDark = (props: Props) => (
  <Icon
    title="BlocksDark"
    viewBox="0 0 242 282"
    data-license="CC-BY 4.0"
    data-source="Labs."
    {...props}>
    <g>
      <title>Blokker</title>
      <g stroke="none" fill="none" strokeWidth="1" fillRule="evenodd">
        <g>
          <g>
            <polygon
              fill="#FFFFFF"
              points="1.9 70.6 61.2 36.5 120.9 70.6 121.1 141.8 179.8 174.9 240.1 140.3 240.1 211.2 121.1 279 1.9 209.9 1.9 126.6"
            />
            <polygon
              fill="#E7D2FC"
              points="121 3.1 240.1 71.6 240.1 141.4 180.8 175.4 121 141.4 121 71.9 61.9 38.1"
            />
            <line x1="179.8" y1="173.9" x2="179.8" y2="106.6" />
            <polygon points="121.9 140.8 121.9 140.9 122 140.9" />
            <polygon points="181.8 106.6 181.8 173.5 238.9 140.5 238.9 73.6" />
            <path
              d="M121.6,0.8 L121,0.4 L0.6,70.1 L0.1,70.3 L0.1,212.3 L120.6,281.7 L121,281.9 L241.5,212.5 L242,212.3 L242,70.3 L121.6,0.8 Z M237.9,75.4 L237.9,139.9 L182.8,171.7 L182.8,107.2 L237.9,75.4 Z M237.9,144.7 L237.9,210 L122.9,276.2 L122.9,211 L237.9,144.7 Z M118.9,210.8 L118.9,276.2 L62.9,243.9 L62.9,178.5 L118.9,210.8 Z M65.4,37.1 L121,5.1 L236.3,71.6 L180.7,103.7 L65.4,37.1 Z M178.8,107.2 L178.8,172.1 L122.9,139.9 L122.9,75 L178.8,107.2 Z M118.9,74.8 L118.9,140 L62.9,172.3 L62.9,107.1 L118.9,74.8 Z M176.3,175.4 L121,207.3 L65.6,175.4 L120.9,143.5 L176.3,175.4 Z M116.8,71.4 L60.9,103.6 L5.6,71.7 L61.4,39.5 L116.8,71.4 Z M58.9,107.1 L58.9,241.5 L4,209.9 L4,75.5 L58.9,107.1 Z"
              fill="#603091"
              fillRule="nonzero"
            />
          </g>
        </g>
      </g>
    </g>
  </Icon>
);

export default BlocksDark;
