/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const BlocksLight = props => (
  <Icon
    title="BlocksLight"
    viewBox="0 0 243 282"
    data-license="CC-BY 4.0"
    data-source="Labs."
    {...props}>
    <g>
      <title>Blokker</title>
      <g stroke="none" fill="none" strokeWidth="1" fillRule="evenodd">
        <g>
          <g>
            <polygon
              fill="#E7D2FC"
              points="121.4 2.8 240.5 71.3 240.5 141.1 181.3 175.2 121.4 141.1 121.4 71.6 62.3 37.9"
            />
            <g>
              <line x1="180.2" y1="173.7" x2="180.2" y2="106.4" />
              <polygon points="62.3 173.9 120.3 140.4 120.3 72.8 62.3 106.3" />
              <polygon points="122.3 140.6 122.3 140.7 122.4 140.7" />
              <polygon points="178.8 175.2 121.4 142.1 64.1 175.2 121.4 208.3" />
              <polygon points="182.2 106.4 182.2 173.3 239.3 140.3 239.3 73.4" />
              <polygon points="61.3 104.6 119.1 71.2 61.8 38.1 4 71.5" />
              <polygon points="239.3 210.3 239.3 142.6 122.3 210.1 122.3 277.8" />
              <polygon points="60.3 106.3 3.4 73.5 3.4 210.3 60.3 243.1" />
              <polygon points="120.3 210 62.3 176.5 62.3 244.3 120.3 277.7" />
              <path
                d="M121.9,0.5 L121.4,0.2 L0.9,69.8 L0.4,70.1 L0.4,212.1 L120.8,281.5 L121.3,281.8 L241.8,212.3 L242.3,212 L242.3,70 L121.9,0.5 Z M119.3,210.6 L119.3,276.1 L63.3,243.8 L63.3,178.3 L119.3,210.6 Z M117.2,71.2 L61.3,103.4 L6,71.5 L61.8,39.3 L117.2,71.2 Z M181.1,103.5 L65.8,36.9 L121.4,4.9 L236.7,71.4 L181.1,103.5 Z M238.3,144.4 L238.3,209.8 L123.3,276 L123.3,210.7 L238.3,144.4 Z M121.3,143.3 L176.7,175.2 L121.4,207.1 L66,175.2 L121.3,143.3 Z M179.2,107 L179.2,172 L123.3,139.8 L123.3,74.8 L179.2,107 Z M119.3,74.5 L119.3,139.8 L63.3,172.1 L63.3,106.8 L119.3,74.5 Z M183.2,171.6 L183.2,107 L238.3,75.2 L238.3,139.8 L183.2,171.6 Z M59.3,106.9 L59.3,241.4 L4.4,209.8 L4.4,75.2 L59.3,106.9 Z"
                fill="#FFFFFF"
                fillRule="nonzero"
              />
            </g>
          </g>
        </g>
      </g>
    </g>
  </Icon>
);

export default BlocksLight;
