/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const BookOpen = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Knowit" {...props}>
    <g>
      <path
        fill="none"
        d="M12 19.3099H4.81C3.68 19.3099 2.75 18.3799 2.75 17.2499V6.96991C2.75 5.83991 3.68 4.90991 4.81 4.90991H5.72"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fill="none"
        d="M12.0001 4.91993V19.3099C11.6901 18.8099 10.7701 17.4799 8.99008 16.7499C8.18008 16.4199 7.41009 16.31 6.81009 16.28C6.26009 16.26 5.84009 15.8 5.84009 15.26V3.86994C5.84009 3.28994 6.31011 2.81997 6.89011 2.83997C7.46011 2.85997 8.14009 2.94993 8.87009 3.16993C10.4001 3.61993 11.4501 4.42993 12.0001 4.91993Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fill="none"
        d="M21.25 6.96991V17.2499C21.25 18.3799 20.32 19.3099 19.19 19.3099H12V4.91992H19.19C20.32 4.91992 21.25 5.83991 21.25 6.96991Z"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fill="none"
        d="M15.0701 7.96997H18.1801"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fill="none"
        d="M15.0701 12.1099H18.1801"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        fill="none"
        d="M15.0701 16.26H18.1801"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </g>
  </Icon>
);

export default BookOpen;
