/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const BookOutlined = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 22 16" {...props}>
    <path d="M13 5.7V4.4a8.8 8.8 0 0 1 6-.3v1.1a7.1 7.1 0 0 0-6 .5m0 5.5V9.8a9 9 0 0 1 6-.3v1.1a7.1 7.1 0 0 0-6 .5Zm0-2.8V7.2a8.8 8.8 0 0 1 6-.4V8a7.1 7.1 0 0 0-6 .4m-7.8 4.1a10.9 10.9 0 0 1 5.1 1.3V3a9.5 9.5 0 0 0-5.1-1.6c-.6 0-1.3 0-1.9.2l-1.8.6v10.9a7 7 0 0 1 1.8-.5 12 12 0 0 1 1.9-.2Zm6.6 1.3a10 10 0 0 1 5-1.3 13.4 13.4 0 0 1 3.7.6V2.3l-1.8-.6a9.2 9.2 0 0 0-4.5.2c-.9.3-1.6.7-2.4 1.2zM11 16a10 10 0 0 0-5.8-2l-1.8.3-1.8.5a1 1 0 0 1-1 0c-.4-.3-.6-.6-.6-1V2c0-.2 0-.4.2-.6 0-.2.3-.4.5-.5a9.7 9.7 0 0 1 4.5-1 9.8 9.8 0 0 1 5.9 1.7c.8-.6 1.7-1 2.7-1.3a10.7 10.7 0 0 1 7.5.6A1.3 1.3 0 0 1 22 2v11.6c0 .5-.2.8-.6 1a1 1 0 0 1-1 .1l-1.8-.6-1.8-.2a11 11 0 0 0-5.8 2Z" />
  </Icon>
);
export default BookOutlined;
