/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const BookOpen = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Knowit" {...props}>
    <g>
      <path
        stroke="currentColor"
        fill="none"
        d="M12 19.3H4.8a2 2 0 0 1-2-2V7c0-1.2.9-2 2-2h1"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
      <path
        stroke="currentColor"
        fill="none"
        d="M12 5v14.3a6.5 6.5 0 0 0-5.2-3 1 1 0 0 1-1-1V3.9c0-.6.5-1 1-1a8.2 8.2 0 0 1 5.1 2Zm9.3 2v10.2c0 1.2-1 2.1-2.1 2.1H12V5h7.2c1.1 0 2 1 2 2ZM15 8h3.2M15 12.1h3.2M15 16.3h3.2"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="1.5"
      />
    </g>
  </Icon>
);

export default BookOpen;
