/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Comment = (props: Props) => (
  <Icon viewBox="0 0 20 20" data-license="Apache License 2.0" data-source="Knowit" {...props}>
    <g>
      <path
        d="M6.44708 10.891C6.93907 10.891 7.33789 10.4922 7.33789 10.0002C7.33789 9.5082 6.93907 9.10938 6.44708 9.10938C5.9551 9.10938 5.55627 9.5082 5.55627 10.0002C5.55627 10.4922 5.9551 10.891 6.44708 10.891Z"
        fill="#444444"
      />
      <path
        d="M10.002 10.891C10.494 10.891 10.8928 10.4922 10.8928 10.0002C10.8928 9.5082 10.494 9.10938 10.002 9.10938C9.51003 9.10938 9.11121 9.5082 9.11121 10.0002C9.11121 10.4922 9.51003 10.891 10.002 10.891Z"
        fill="#444444"
      />
      <path
        d="M13.5567 10.891C14.0487 10.891 14.4475 10.4922 14.4475 10.0002C14.4475 9.5082 14.0487 9.10938 13.5567 9.10938C13.0647 9.10938 12.6659 9.5082 12.6659 10.0002C12.6659 10.4922 13.0647 10.891 13.5567 10.891Z"
        fill="#444444"
      />
      <path
        d="M16.6064 12.9797C16.5312 13.1475 16.5212 13.3346 16.5736 13.506L17.0682 16.8768L13.7422 16.3846C13.5884 16.3618 13.4314 16.3874 13.2928 16.4578C12.3033 16.9604 11.1824 17.25 10 17.25C5.99475 17.25 2.75 14.0052 2.75 10C2.75 5.99475 5.99475 2.75 10 2.75C14.0052 2.75 17.25 5.99475 17.25 10C17.25 11.0559 17.0154 12.0674 16.6064 12.9797Z"
        stroke="#444444"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </g>
  </Icon>
);

export default Comment;
