/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Comment = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Knowit" viewBox="0 0 20 20" {...props}>
    <path
      fill="#444"
      d="M6.4 10.9a.9.9 0 1 0 0-1.8.9.9 0 0 0 0 1.8m3.6 0A.9.9 0 1 0 10 9a.9.9 0 0 0 0 1.8Zm3.6 0a.9.9 0 1 0 0-1.8.9.9 0 0 0 0 1.8"
    />
    <path
      fill="none"
      stroke="#444"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.5}
      d="M16.6 13v.5L17 17l-3.4-.5h-.4a7.3 7.3 0 1 1 3.3-3.4Z"
    />
  </Icon>
);
export default Comment;
