/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Cross = props => (
  <Icon viewBox="0 0 24 24" data-license="CC-BY 4.0" {...props}>
    <g>
      <path d="M.708 22.449l.664.665L12 12.486l10.628 10.628.664-.665-10.628-10.628L23.292 1.193l-.664-.664L12 11.157 1.372.529l-.664.664 10.628 10.628z" />
    </g>
  </Icon>
);

export default Cross;
