/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Download = props => (
  <Icon
    title="Download"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g>
      <path d="M19 9h-4V3H9v6H5l7 7 7-7zM5 18v2h14v-2H5z" />
      <path d="M0 0h24v24H0z" fill="none" />
    </g>
  </Icon>
);

export default Download;
