/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const Email = (props: Props) => (
  <Icon fill="none" data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      d="M4 20c-.55 0-1.02-.2-1.41-.59-.4-.39-.59-.86-.59-1.41V6c0-.55.2-1.02.59-1.41C2.98 4.19 3.45 4 4 4h16c.55 0 1.02.2 1.41.59.4.39.59.86.59 1.41v12c0 .55-.2 1.02-.59 1.41-.39.4-.86.59-1.41.59zm8-7 8-5V6l-8 5-8-5v2z"
    />
  </Icon>
);
export default Email;
