/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Esc = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M4 15.6V9.1h4v1.3H5.6v1.3h2.2v1.2H5.5v1.5h2.7v1.2H4Zm7.5.2a3.7 3.7 0 0 1-2.4-1l.8-1 .8.5.8.2c.3 0 .5 0 .7-.2l.2-.4v-.3l-.2-.2-.3-.2-.4-.1-.9-.4a2.5 2.5 0 0 1-.9-.6 1.7 1.7 0 0 1-.4-1.2c0-.2 0-.5.2-.7.1-.3.3-.5.5-.6l.7-.4c.3-.2.6-.2 1-.2a3 3 0 0 1 2 .9l-.7.9-.7-.4-.7-.1a1 1 0 0 0-.6.1l-.2.5v.2l.3.2.3.2.4.1.8.4c.4.1.8.3 1 .6.2.3.3.7.3 1.1a1.9 1.9 0 0 1-.6 1.5l-.8.4a3 3 0 0 1-1 .2Zm6.3 0c-.5 0-.8-.1-1.2-.3A2.7 2.7 0 0 1 15 14a4 4 0 0 1-.3-1.5c0-.5.1-1 .3-1.4.1-.4.4-.8.7-1.1.2-.3.6-.5 1-.7a3 3 0 0 1 1.1-.2c.4 0 .8 0 1.1.3.4.1.6.3.9.5l-.8 1-.5-.4-.7-.1-.6.1-.5.4a2 2 0 0 0-.3.7l-.2.9c0 .6.2 1.2.5 1.5.3.4.6.6 1.1.6.3 0 .5 0 .7-.2l.6-.4.8.9a3 3 0 0 1-2.1 1Z" />
    </g>
  </Icon>
);

export default Esc;
