/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const Explanation = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="CC-BY 4.0" data-source="Labs AS" {...props}>
    <g>
      <path
        fill="currentColor"
        d="M15.6 12.8c.5-3.3 4.1-3.5 4.7-5.4.3-1 0-2-1.2-2.2-.9-.3-1.7-.1-2.6.4l-1-1.7a5.2 5.2 0 0 1 4.4-.7c2.3.7 3.6 2.4 2.9 4.7-.8 2.7-4.5 2.7-5 5.5l-2.2-.6Zm-1.5 3c.3-1 1.2-1.5 2.1-1.2 1 .3 1.4 1.2 1.1 2.2-.3 1-1.2 1.4-2.1 1.1-1-.2-1.4-1.2-1.1-2.1Zm-7.2.3C5.3 12.3 9.3 10 8.7 7.4c-.3-1.3-1.4-2-2.8-1.6a4 4 0 0 0-2.7 2L1 6.6c.9-1.6 2.4-3 4.5-3.4 3-.7 5.7.4 6.4 3.3.8 3.4-3.4 5.6-2.1 9l-3 .6Zm.3 4.2a2 2 0 0 1 1.6-2.6c1.2-.2 2.4.5 2.7 1.7a2 2 0 0 1-1.6 2.5c-1.2.3-2.4-.4-2.7-1.6Z"
        fillRule="evenodd"
        clipRule="evenodd"
      />
    </g>
  </Icon>
);

export default Explanation;
