/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const FacebookFilled = (props: Props) => (
  <Icon fill="none" data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M22 12.06a10 10 0 1 0-11.56 9.88v-6.99H7.9v-2.89h2.54v-2.2c0-2.5 1.49-3.9 3.77-3.9 1.1 0 2.24.2 2.24.2v2.46H15.2c-1.24 0-1.63.77-1.63 1.56v1.88h2.78l-.45 2.9h-2.33v6.98A10 10 0 0 0 22 12.06"
      clipRule="evenodd"
    />
  </Icon>
);
export default FacebookFilled;
