/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Facebook = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="SIL Open Font License 1.1"
    data-source="Material Community Icons"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M17 2v4h-2c-.7 0-1 .8-1 1.5V10h3v4h-3v8h-4v-8H7v-4h3V6a4 4 0 0 1 4-4z" />
  </Icon>
);
export default Facebook;
