/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const FeideText = (props: Props) => (
  <Icon viewBox="0 0 113.7 39" data-license="CC-BY 4.0" data-source="Feide" {...props}>
    <g>
      <path d="M28 20.3h4.2v10.2H28zm-9.8 3H14v11.5H4.2V20.3H0V39h32.2v-4.2h-14V23.3z" className="cls-1" />
      <circle cx="16.1" cy="16.5" r="2.5" className="cls-1" />
      <path
        d="M16.1 4.2A11.9 11.9 0 0 1 28 16.1h4.3a16.1 16.1 0 0 0-32.3 0h4.3A11.9 11.9 0 0 1 16 4.2Z"
        className="cls-1"
      />
      <path d="M53.3 21.6h-7.7v-6.1h10.1v-3.4H42v22.7h3.6V25h7.7v-3.4zM77.8 10a2.5 2.5 0 1 0 2.5 2.6 2.5 2.5 0 0 0-2.5-2.5Zm-5.3 7.8v3.4H76v10.1h-4.3v3.4h10.2v-3.4h-2.3V17.8h-7.1zm25 16.9V10.5H94v8.8l-.3-.3a4 4 0 0 0-3.3-1.6c-3.4 0-5.8 2.7-5.8 6.5v4.7c0 3.8 2.4 6.5 5.8 6.5a4.1 4.1 0 0 0 3.4-1.6l.2-.3v1.5ZM94 30a3.3 3.3 0 0 1-2.9 1.6 2.8 2.8 0 0 1-3-3.1v-4.7a2.8 2.8 0 0 1 3-3.2 3.3 3.3 0 0 1 2.9 1.7V30Zm-24.8-2.2v-4.5c0-3.5-2.7-6.1-6.5-6.1S56 19.8 56 23.3V29c0 3.5 2.9 6 6.6 6a6.5 6.5 0 0 0 6.2-3.6l-3.4-1.5a2.8 2.8 0 0 1-2.8 2 2.8 2.8 0 0 1-3-3v-1Zm-9.4-4.5a3 3 0 0 1 5.8 0v1.3h-5.8Zm53.9 4.5v-4.5c0-3.5-2.7-6.1-6.5-6.1s-6.6 2.6-6.6 6.1V29c0 3.5 2.9 6 6.6 6a6.5 6.5 0 0 0 6.2-3.6l-3.4-1.5a2.8 2.8 0 0 1-2.8 2 2.8 2.8 0 0 1-3-3v-1Zm-9.4-4.5a3 3 0 0 1 5.8 0v1.3h-5.8Z" />
    </g>
  </Icon>
);

export default FeideText;
