/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Feide = (props: Props) => (
  <Icon viewBox="-7 -2 45 45" data-license="CC-BY 4.0" data-source="Feide" {...props}>
    <g>
      <rect x="27.99" y="20.34" width="4.24" height="10.18" />
      <polygon points="18.23 23.31 13.99 23.31 13.99 34.76 4.24 34.76 4.24 20.34 0 20.34 0 35.61 0.02 35.61 0.02 39 32.23 39 32.23 34.76 18.23 34.76 18.23 23.31" />
      <circle cx="16.11" cy="16.53" r="2.54" />
      <path d="M16.11,4.24A11.87,11.87,0,0,1,28,16.1h4.25A16.11,16.11,0,0,0,0,16.1H4.25A11.87,11.87,0,0,1,16.11,4.24Z" />
    </g>
  </Icon>
);

export default Feide;
