/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const FileEditFill = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M21 15.24v5.77a1 1 0 0 1-1 .99H4a1 1 0 0 1-1-1V9h6a1 1 0 0 0 1-1V2h10a1 1 0 0 1 1 1v3.76l-9 9V20h4.24zm.78-6.43 1.41 1.41L15.41 18H14v-1.41zM3 7l5-5v5z" />
  </Icon>
);
export default FileEditFill;
