/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const FileDownloadOutline = props => (
  <Icon
    title="FileDownloadOutline"
    viewBox="0 0 24 24"
    data-license="SIL Open Font License 1.1"
    data-source="Material Community Icons"
    {...props}>
    <g>
      <path d="M14,2L20,8V20A2,2 0 0,1 18,22H6A2,2 0 0,1 4,20V4A2,2 0 0,1 6,2H14M18,20V9H13V4H6V20H18M12,19L8,15H10.5V12H13.5V15H16L12,19Z" />
    </g>
  </Icon>
);

export default FileDownloadOutline;
