/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const FileDownloadOutline = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="SIL Open Font License 1.1" data-source="Material Community Icons" {...props}>
    <g>
      <path d="m14 2 6 6v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8m4 18V9h-5V4H6v16h12m-6-1-4-4h2.5v-3h3v3H16l-4 4Z" />
    </g>
  </Icon>
);

export default FileDownloadOutline;
