/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const FooterHeaderIcon = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Keyteq" viewBox="0 0 76 76" {...props}>
    <path d="M46.4 46.4 15 61l14.6-31.4L61 15zM38 0a38 38 0 1 0 0 76 38 38 0 0 0 0-76m0 34a4 4 0 1 0 0 8 4 4 0 0 0 0-8" />
  </Icon>
);
export default FooterHeaderIcon;
