/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const FooterHeaderIcon = (props: Props) => (
  <Icon title="FooterHeaderIcon" viewBox="0 0 76 76" data-license="CC-BY 4.0" data-source="Keyteq" {...props}>
    <g>
      <title>Footer icon</title>
      <g>
        <path d="M46.395,46.395 L15,61 L29.605,29.605 L61,15 L46.395,46.395 Z M38,0 C17.0131795,0 0,17.0131795 0,38 C0,48.0782266 4.00355993,57.7436753 11.1299423,64.8700577 C18.2563247,71.9964401 27.9217734,76 38,76 C48.0782266,76 57.7436753,71.9964401 64.8700577,64.8700577 C71.9964401,57.7436753 76,48.0782266 76,38 C76,27.9217734 71.9964401,18.2563247 64.8700577,11.1299423 C57.7436753,4.00355993 48.0782266,0 38,0 L38,0 Z M38,34 C35.790861,34 34,35.790861 34,38 C34,40.209139 35.790861,42 38,42 C40.209139,42 42,40.209139 42,38 C42,35.790861 40.209139,34 38,34 Z" />
      </g>
    </g>
  </Icon>
);

export default FooterHeaderIcon;
