/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Forum = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 20 20" {...props}>
    <path d="m5 16-.7-.3c-.2-.3-.3-.5-.3-.8v-2.4h12.5V4H19a1 1 0 0 1 1 1v15l-4-4zm-5-1V1L.3.4C.5.1.8 0 1 0h13c.2 0 .5.1.7.3.2.3.3.5.3.8v8.8c0 .3-.1.5-.3.8a1 1 0 0 1-.7.3H4z" />
  </Icon>
);
export default Forum;
