/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Fullscreen = props => (
  <Icon
    viewBox="0 0 16 16"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g fill="#FFF" fill-rule="evenodd" transform="rotate(135 10.621 8.879)">
      <g transform="translate(8)">
        <rect width="3" height="5" x="2" y="3"/>
        <polygon points="3.5 .5 7 4 0 4"/>
      </g>
      <g transform="rotate(90 7.536 15.5)">
        <rect width="3" height="5" x="2" y="3"/>
        <polygon points="3.5 .5 7 4 0 4"/>
      </g>
      <g transform="rotate(-90 7.5 7)">
        <rect width="3" height="5" x="2" y="3"/>
        <polygon points="3.5 .5 7 4 0 4"/>
      </g>
      <g transform="rotate(-180 7.75 11.25)">
        <rect width="3" height="5" x="2" y="3"/>
        <polygon points="3.5 .5 7 4 0 4"/>
      </g>
    </g>
  </Icon>
);

export default Fullscreen;
