/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Fullscreen = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 48 48" {...props}>
    <path d="M14 28h-4v10h10v-4h-6zm-4-8h4v-6h6v-4H10zm24 14h-6v4h10V28h-4zm-6-24v4h6v6h4V10z" />
  </Icon>
);
export default Fullscreen;
