/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Grid = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 48 48" {...props}>
    <path d="M8 16h8V8H8zm12 24h8v-8h-8zM8 40h8v-8H8zm0-12h8v-8H8zm12 0h8v-8h-8zM32 8v8h8V8zm-12 8h8V8h-8zm12 12h8v-8h-8zm0 12h8v-8h-8z" />
  </Icon>
);
export default Grid;
