/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const HelpCircleDual = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Keyteq" viewBox="0 0 24 24" {...props}>
    <path
      d="M12.2.7a11.3 11.3 0 0 1 9.9 5.7A11.3 11.3 0 0 1 18 22c-1.9 1-3.8 1.6-5.9 1.6A11.3 11.3 0 0 1 2.3 18a11.2 11.2 0 0 1 0-11.6A11.3 11.3 0 0 1 12.2.7"
      className="HelpCircleDual-background"
    />
    <path
      d="M14 12c.3-.2.4-.4.5-.7.2-.2.2-.5.2-.8 0-.5-.1-1-.4-1.4A2.8 2.8 0 0 0 12 7.8c-.5 0-1 .1-1.4.4a2.8 2.8 0 0 0-1.3 2.3h1.3c0-.4.2-.7.4-1 .3-.2.6-.4 1-.4s.7.2 1 .4c.2.3.4.6.4 1 0 .3-.2.7-.4 1l-.9.8a3 3 0 0 0-.8 2v.3h1.4c0-.5 0-.9.2-1.2l.6-.7.6-.7Zm-1.4 5.3V16h-1.3v1.4z"
      className="HelpCircleDual-symbol"
    />
  </Icon>
);
export default HelpCircleDual;
