/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const HomeOutline = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <g>
        <path d="M5.5 19.5H9.25V13.25H14.75V19.5H18.5V9.75L12 4.875L5.5 9.75V19.5ZM4 21V9L12 3L20 9V21H13.25V14.75H10.75V21H4Z" />
      </g>
    </g>
  </Icon>
);

export default HomeOutline;
