/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const Home = (props: Props) => (
  <Icon viewBox="0 0 48 48" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M20 40V28h8v12h10V24h6L24 6 4 24h6v16z" />
    </g>
  </Icon>
);

export default Home;
