/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Home = props => (
  <Icon
    viewBox="0 0 24 24"
    data-license="CC-BY 4.0"
    data-source="Netlife"
    {...props}>
    <g>
      <path d="M20,20v-8h2v0L12,3L2,12v0h2v8c0,0.6,0.4,1,1,1h5v-7h4v7h5C19.6,21,20,20.6,20,20z" />
    </g>
  </Icon>
);

export default Home;
