/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const HomeLine = (props: Props) => (
  <Icon fill="currentColor" viewBox="0 0 24 24" {...props}>
    <path d="M19 21H5a1 1 0 0 1-1-1v-9H1l10.33-9.39a1 1 0 0 1 1.34 0L23 11h-3v9a1 1 0 0 1-1 1M6 19h12V9.16L12 3.7 6 9.16z" />
  </Icon>
);
export default HomeLine;
