/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const HomeFill = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M21 20a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V9.49c0-.31.14-.6.39-.79l8-6.22a1 1 0 0 1 1.22 0l8 6.22a1 1 0 0 1 .39.79z" />
  </Icon>
);
export default HomeFill;
