/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Insights = (props: Props) => (
  <Icon viewBox="0 96 960 960" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M110 906q-29 0-49.5-20.6T40 836q0-28.9 20.5-49.4t49.3-20.5q5.2 0 10.2.5 5 .5 13 2.5l200-200q-2-8-2.5-13t-.5-10.2q0-28.8 20.6-49.3Q371.2 476 400 476t49.4 20.6 20.5 49.6q0 1.8-3 22.8l110 110q8-2 13-2.5t10-.5q5 0 10 .5t13 2.5l160-160q-2-8-2.5-13t-.5-10.2q0-28.8 20.6-49.3Q821.2 426 850 426t49.4 20.6Q920 467.2 920 496t-20.5 49.4-49.3 20.5q-5.2 0-10.2-.5-5-.5-13-2.5L667 723q2 8 2.5 13t.5 10.2q0 28.8-20.6 49.3Q628.8 816 600 816t-49.4-20.5-20.5-49.3q0-5.2.5-10.2.5-5 2.5-13L423 613q-8 2-13 2.5t-10.3.5q-1.7 0-22.7-3L177 813q2 8 2.5 13t.5 10.2q0 28.8-20.6 49.3Q138.8 906 110 906Zm50-442-20.3-43.7L96 400l43.7-20.3L160 336l20.3 43.7L224 400l-43.7 20.3L160 464Zm440-51-30.7-66.3L503 316l66.3-30.7L600 219l30.7 66.3L697 316l-66.3 30.7L600 413Z" />
    </g>
  </Icon>
);

export default Insights;
