/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const KeyboardReturn = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M19 7v4H5.8l3.6-3.6L8 6l-6 6 6 6 1.4-1.4L5.8 13H21V7z" />
  </Icon>
);
export default KeyboardReturn;
