/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const LayoutGridFill = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="M22 13v7a1 1 0 0 1-1 1h-8v-8zm-11 0v8H3a1 1 0 0 1-1-1v-7zm0-10v8H2V4a1 1 0 0 1 1-1zm10 0a1 1 0 0 1 1 1v7h-9V3z" />
  </Icon>
);
export default LayoutGridFill;
