/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const LockedOutline = (props: Props) => (
  <Icon viewBox="0 0 16 21" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M1.5 21c-.41 0-.77-.15-1.06-.44-.3-.3-.44-.65-.44-1.06V8.65c0-.41.15-.77.44-1.06.3-.3.65-.44 1.06-.44h1.75v-2.4c0-1.31.46-2.43 1.39-3.36A4.58 4.58 0 0 1 8 0c1.32 0 2.44.46 3.36 1.39a4.58 4.58 0 0 1 1.39 3.36v2.4h1.75c.41 0 .77.15 1.06.44.3.3.44.65.44 1.06V19.5c0 .41-.15.77-.44 1.06-.3.3-.65.44-1.06.44h-13Zm0-1.5h13V8.65h-13V19.5ZM8 16c.53 0 .99-.18 1.36-.55.38-.37.57-.8.57-1.32 0-.5-.2-.96-.57-1.37A1.8 1.8 0 0 0 8 12.15c-.53 0-.99.2-1.36.61-.38.41-.56.87-.56 1.38 0 .5.18.94.56 1.31.38.37.83.55 1.36.55ZM4.75 7.15h6.5v-2.4c0-.9-.32-1.67-.95-2.3A3.13 3.13 0 0 0 8 1.5c-.9 0-1.67.32-2.3.95-.63.63-.95 1.4-.95 2.3v2.4Z" />
    </g>
  </Icon>
);

export default LockedOutline;
