/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const LogIn = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="CC-BY 4.0" data-source="Labs AS" {...props}>
    <g>
      <path
        d="M19 3H13C12.45 3 12 3.45 12 4C12 4.55 12.45 5 13 5H19V19H13C12.45 19 12 19.45 12 20C12 20.55 12.45 21 13 21H19C20.1 21 21 20.1 21 19V5C21 3.9 20.1 3 19 3Z"
        fill="white"
      />
      <path
        d="M11 9.20997V11H4C3.45 11 3 11.45 3 12C3 12.55 3.45 13 4 13H11V14.79C11 15.24 11.54 15.46 11.85 15.14L14.64 12.35C14.84 12.15 14.84 11.84 14.64 11.64L11.85 8.84997C11.7795 8.78087 11.6901 8.73418 11.5931 8.71579C11.4962 8.69739 11.3959 8.70812 11.305 8.74662C11.2141 8.78512 11.1366 8.84967 11.0823 8.93212C11.0281 9.01458 10.9994 9.11125 11 9.20997Z"
        fill="white"
      />
    </g>
  </Icon>
);

export default LogIn;
