/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const LogOut = (props: Props) => (
  <Icon data-license="CC-BY 4.0" data-source="Labs AS" viewBox="0 0 24 24" {...props}>
    <path d="M5 5h6a1 1 0 0 0 0-2H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h6c.6 0 1-.4 1-1s-.4-1-1-1H5z" />
    <path d="M20.6 11.7 18 8.9a.5.5 0 0 0-.9.3V11h-7a1 1 0 0 0-1 1c0 .6.4 1 1 1h7v1.8c0 .4.5.7.9.3l2.7-2.8c.2-.1.2-.5 0-.7Z" />
  </Icon>
);
export default LogOut;
