/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const Menu = props => (
  <Icon
    title="Menu"
    viewBox="0 0 30.4 30.5"
    data-license="CC-BY 4.0"
    data-source="Netlife"
    {...props}>
    <g>
      <rect x="1.8" y="1.8" width="6.8" height="6.8" />
      <rect x="11.8" y="1.8" width="6.8" height="6.8" />
      <rect x="21.8" y="1.8" width="6.8" height="6.8" />
      <rect x="1.8" y="11.8" width="6.8" height="6.8" />
      <rect x="11.8" y="11.8" width="6.8" height="6.8" />
      <rect x="21.8" y="11.8" width="6.8" height="6.8" />
      <rect x="1.8" y="21.8" width="6.8" height="6.8" />
      <rect x="11.8" y="21.8" width="6.8" height="6.8" />
      <rect x="21.8" y="21.8" width="6.8" height="6.8" />
    </g>
  </Icon>
);

export default Menu;
