/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Pin = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path fill="none" d="M0 0h24v24H0z" />
    <path
      fillRule="evenodd"
      d="M16 9V4h1a1 1 0 0 0 0-2H7a1 1 0 0 0-1 1c0 .6.5 1 1 1h1v5a3 3 0 0 1-3 3v2h6v7l1 1 1-1v-7h6v-2a3 3 0 0 1-3-3"
    />
  </Icon>
);
export default Pin;
