/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const PinOutlined = (props: Props) => (
  <Icon viewBox="0 0 12 20" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="m9.8 9.8 2.2 2v1.4H6.7v6L6 20l-.8-.8v-6H0v-1.5l2-1.9V1.5H.7V0h10.4v1.5H9.8v8.3Zm-7.8 2h7.8l-1.5-1.5V1.5H3.5v8.8L2 11.8Z" />
    </g>
  </Icon>
);

export default PinOutlined;
