/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon from '../Icon';

interface Props {
  children?: ReactNode;
}

const Play = (props: Props) => (
  <Icon
    title="Play"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g>
      <path d="M8.016 5.016l10.969 6.984-10.969 6.984v-13.969z" />
    </g>
  </Icon>
);

export default Play;
