/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ProfilePerson = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 20 20" {...props}>
    <path d="M3.5 15.6a11.4 11.4 0 0 1 9.8-1.5l3.2 1.5a8.8 8.8 0 0 0 2-5.6A8.2 8.2 0 0 0 10 1.5 8.2 8.2 0 0 0 1.5 10a9 9 0 0 0 2 5.6m6.5-4.8c-1 0-1.8-.4-2.4-1-.7-.7-1-1.5-1-2.5s.3-1.8 1-2.4c.6-.7 1.4-1 2.4-1s1.8.3 2.4 1c.7.7 1 1.5 1 2.4 0 1-.3 1.8-1 2.5-.6.6-1.4 1-2.4 1m0 9.2a9.8 9.8 0 0 1-7.1-3 10 10 0 0 1 0-14A10.3 10.3 0 0 1 10 0a9.7 9.7 0 0 1 7 3 10.1 10.1 0 0 1 2.2 10.9 10.3 10.3 0 0 1-5.3 5.3c-1.2.5-2.5.8-4 .8Z" />
  </Icon>
);
export default ProfilePerson;
