/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const ProfilePersonOutlined = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 20 20" {...props}>
    <path d="M3.5 15.6c1.1-.7 2.1-1.3 3.2-1.7a9.4 9.4 0 0 1 6.7 0c1 .4 2 1 3 1.7a8.8 8.8 0 0 0 2.1-5.6A8.2 8.2 0 0 0 10 1.5 8.2 8.2 0 0 0 1.5 10a9 9 0 0 0 2 5.6m6.5-4.8c-1 0-1.8-.4-2.4-1-.7-.7-1-1.5-1-2.5s.3-1.8 1-2.4c.6-.7 1.4-1 2.4-1s1.8.3 2.4 1c.7.7 1 1.5 1 2.4 0 1-.3 1.8-1 2.5-.6.6-1.4 1-2.4 1m0 9.2a9.7 9.7 0 0 1-7-3 10.2 10.2 0 0 1-3-7 9.6 9.6 0 0 1 3-7 10.2 10.2 0 0 1 7-3 9.6 9.6 0 0 1 7 3 10.2 10.2 0 0 1 3 7 9.7 9.7 0 0 1-3 7 10.2 10.2 0 0 1-7 3m0-1.5a8 8 0 0 0 5.3-1.8c-.9-.6-1.7-1-2.6-1.4a7.9 7.9 0 0 0-5.4 0c-.9.3-1.7.8-2.6 1.4a8 8 0 0 0 5.3 1.8m0-9.3c.6 0 1-.1 1.4-.5.3-.3.5-.8.5-1.4 0-.5-.2-1-.5-1.4-.4-.3-.8-.5-1.4-.5-.6 0-1 .2-1.4.5-.3.4-.5.9-.5 1.4 0 .6.2 1 .5 1.4.4.4.8.6 1.4.6Z" />
  </Icon>
);
export default ProfilePersonOutlined;
