/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const RouteLine = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="m8.47 19.48 6.5.03a4.5 4.5 0 1 0 .04-9l-7-.03a2.5 2.5 0 0 1 .02-5l6.67.03a3 3 0 1 0 .01-2l-6.67-.03a4.5 4.5 0 1 0-.04 9l7 .03a2.5 2.5 0 1 1-.03 5l-6.5-.03.02-3-5.02 3.98 4.98 4.02zm8.06-14.96a1 1 0 1 1 2 .01 1 1 0 0 1-2 0" />
  </Icon>
);
export default RouteLine;
