/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const RouteFill = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="m9.9 20.04 6.5.03a4.5 4.5 0 1 0 .05-9l-7-.03a2.5 2.5 0 1 1 .02-5l6.67.03a3 3 0 1 0 .01-2l-6.67-.03a4.5 4.5 0 1 0-.04 9l7 .03a2.5 2.5 0 1 1-.02 5l-6.5-.03.01-3-5.02 3.98 4.98 4.02z" />
  </Icon>
);
export default RouteFill;
