/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const RouteFill = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M9 20h6.5a4.5 4.5 0 1 0 0-9h-7a2.5 2.5 0 0 1 0-5h6.67a3 3 0 1 0 0-2H8.5a4.5 4.5 0 1 0 0 9h7a2.5 2.5 0 0 1 0 5H9v-3l-5 4 5 4z" />
  </Icon>
);
export default RouteFill;
