/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const RssFeed = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path fill="none" d="M0 0h24v24H0z" />
      <circle cx="6.2" cy="17.8" r="2.2" />
      <path d="M4 4.4v2.9c7 0 12.7 5.7 12.7 12.7h2.9c0-8.6-7-15.6-15.6-15.6zm0 5.7v2.8a7 7 0 0 1 7 7.1h3c0-5.5-4.4-9.9-9.9-9.9z" />
    </g>
  </Icon>
);

export default RssFeed;
