/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const Sad = (props: Props) => (
  <Icon viewBox="0 0 48 48" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M31 22a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-14 0a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm7-18a20 20 0 1 0 0 40 20 20 0 0 0 0-40zm0 36a16 16 0 1 1 0-32 16 16 0 0 1 0 32zm0-12a11 11 0 0 0-10.2 7H17c1.4-2.4 4-4 6.9-4s5.5 1.6 6.9 4h3.3A11 11 0 0 0 24 28z" />
    </g>
  </Icon>
);

export default Sad;
