/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const SearchLine = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path d="m18.03 16.62 4.28 4.28-1.41 1.41-4.28-4.28a9 9 0 1 1 1.41-1.41m-2-.75a7 7 0 1 0-.15.15z" />
  </Icon>
);
export default SearchLine;
