/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const SubdirectoryArrow = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path fill="none" d="M0 0h24v24H0V0z" />
      <path d="m19 15-6 6-1.4-1.4 3.6-3.6H4V4h2v10h9.2l-3.6-3.6L13 9l6 6z" />
    </g>
  </Icon>
);

export default SubdirectoryArrow;
