/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const TagOutlined = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 21 21" {...props}>
    <path d="M12 19.6c-.3.3-.7.4-1.1.4-.4 0-.8-.1-1.1-.4L.4 10.2c-.1-.2-.3-.3-.3-.5L0 9V1.5A1.5 1.5 0 0 1 1.5 0h8.2l.6.4 9.3 9.3c.3.4.4.7.4 1.2 0 .4-.1.8-.4 1L12 19.7Zm-1-1 7.6-7.7L9 1.5H1.5v7.6l9.4 9.5ZM4 5.4c.4 0 .7-.1 1-.4.2-.2.3-.5.3-.9 0-.3-.1-.7-.4-1-.2-.2-.5-.3-.9-.3-.3 0-.6.1-.9.4-.2.2-.4.5-.4.9s.2.7.4 1c.3.2.6.3 1 .3Z" />
  </Icon>
);
export default TagOutlined;
