/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ThreeSixty = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path fill="none" d="M0 0h24v24H0z" />
    <path d="M12 7C6.5 7 2 9.2 2 12c0 2.2 3 4.1 7 4.8V20l4-4-4-4v2.7c-3.1-.5-5-1.9-5-2.7 0-1 3-3 8-3s8 2 8 3c0 .7-1.5 1.9-4 2.5v2c3.5-.7 6-2.5 6-4.5 0-2.8-4.5-5-10-5" />
  </Icon>
);
export default ThreeSixty;
