/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const Time = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 48 48" {...props}>
    <path d="M24 4a20 20 0 1 0 0 40 20 20 0 0 0 0-40m0 36a16 16 0 1 1 0-32 16 16 0 0 1 0 32m1-26h-3v12l10.5 6.3 1.5-2.5-9-5.3z" />
  </Icon>
);
export default Time;
