/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Twitter = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="SIL Open Font License 1.1" data-source="Material Community Icons" {...props}>
    <g>
      <path d="M22.5 6c-.8.3-1.6.6-2.5.7.9-.5 1.6-1.4 1.9-2.4-.8.5-1.8.9-2.7 1a4.3 4.3 0 0 0-7.3 4C8.2 9 5 7.3 3 4.8a4.2 4.2 0 0 0 1.3 5.7 5 5 0 0 1-2-.5c0 2.1 1.6 3.8 3.5 4.2a4.2 4.2 0 0 1-2 .1c.6 1.7 2.2 3 4 3A8.5 8.5 0 0 1 1.6 19c2 1.2 4.2 1.9 6.6 1.9A12 12 0 0 0 20.4 8.7v-.6C21.2 7.6 22 7 22.5 6Z" />
    </g>
  </Icon>
);

export default Twitter;
