/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const WarningOutline = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="m12 6 7.5 13h-15L12 6M2.7 18a2 2 0 0 0 1.8 3h15a2 2 0 0 0 1.8-3L13.7 5a2 2 0 0 0-3.4 0L2.7 18zm8.3-7v2c0 .6.5 1 1 1s1-.5 1-1v-2c0-.6-.5-1-1-1s-1 .5-1 1zm0 5h2v2h-2z" />
    </g>
  </Icon>
);

export default WarningOutline;
