/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const Youtube = (props: Props) => (
  <Icon viewBox="0 0 256 256" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <defs>
        <clipPath clipPathUnits="userSpaceOnUse">
          <path d="M0 192h192V0H0Z" />
        </clipPath>
      </defs>
      <g transform="matrix(1.3333333,0,0,-1.3333333,0,256)" clipPath="url(#a)">
        <path d="M78 69.8v52.4L124 96Zm102.3 68.8a22 22 0 0 1-15.5 15.7C151 158 96 158 96 158s-55 0-68.8-3.7a22 22 0 0 1-15.5-15.7C8 124.8 8 96 8 96s0-28.8 3.7-42.6a22 22 0 0 1 15.5-15.7C41 34 96 34 96 34s55 0 68.8 3.7a22 22 0 0 1 15.5 15.7C184 67.2 184 96 184 96s0 28.8-3.7 42.6" />
      </g>
    </g>
  </Icon>
);

export default Youtube;
