/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ZoomOutMap = (props: Props) => (
  <Icon
    fill="currentColor"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 24 24"
    {...props}
  >
    <path
      d="m15 3 2.3 2.3-2.9 2.9 1.4 1.4 2.9-2.9L21 9V3zM3 9l2.3-2.3 2.9 2.9 1.4-1.4-2.9-2.9L9 3H3zm6 12-2.3-2.3 2.9-2.9-1.4-1.4-2.9 2.9L3 15v6zm12-6-2.3 2.3-2.9-2.9-1.4 1.4 2.9 2.9L15 21h6z"
      clipPath="url(#b)"
    />
    <path fill="none" d="M0 0h24v24H0z" clipPath="url(#b)" />
  </Icon>
);
export default ZoomOutMap;
