import { uuid } from '@ndla/util';

export const mockTypeahead = [
  {
    title: 'Albania',
    description:
      'Halfvarsson legger seg flat: – Det ble ingen bra greie ut av det : – Det ble ingen bra greie ut av de. Halfvarsson legger seg flat: – Det ble ingen bra greie ut av det : – Det ble ingen bra greie ut av de',
    image: 'https://placeimg.com/100/200/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Andorra',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/200/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Armenia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Austria',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Azerbaijan',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Belarus',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Belgium',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Bosnia and Herzegovina',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Bulgaria',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Croatia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Czech Republic',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Cyprus',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Denmark',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Estonia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Finland',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'France',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Georgia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Germany',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Greece',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Hungary',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Iceland',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Ireland',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Italy',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Kazakhstan',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Kosovo',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Latvia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Liechtenstein',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Lithuania',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Luxembourg',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Macedonia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Malta',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Moldova',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Monaco',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Montenegro',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Netherlands',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Norway',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Poland',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Portugal',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Romania',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Russia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'San Marino',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Serbia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Slovakia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Slovenia',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Spain',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Sweden',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Switzerland',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Turkey',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Ukraine',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'United Kingdom (UK)',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
  {
    title: 'Vatican City',
    description: 'Lorem ipsum',
    image: 'https://placeimg.com/100/100/nature',
    alt: 'Alt description',
    id: uuid(),
  },
];
