/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ArrowExpandRight = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M4 2H2v20h2v-9h14.2l-5.5 5.5 1.4 1.4L22 12l-8-8-1.3 1.5 5.5 5.5H4z" />
  </Icon>
);
export default ArrowExpandRight;
