/**
 * Copyright (c) 2019-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const ArrowExpandRight = props => (
  <Icon
    title="ArrowExpandRight"
    viewBox="0 0 24 24"
    data-license="Apache License 2.0"
    data-source="Material Design"
    {...props}>
    <g>
      <path d="M4,2H2V22H4V13H18.17L12.67,18.5L14.08,19.92L22,12L14.08,4.08L12.67,5.5L18.17,11H4V2Z" />
    </g>
  </Icon>
);

export default ArrowExpandRight;
