/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ArrowExpandLeft = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M20 22h2V2h-2v9H5.8l5.5-5.5L10 4.1 2 12l8 8 1.3-1.5L5.8 13H20z" />
  </Icon>
);
export default ArrowExpandLeft;
