/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const ArrowExpandRight = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M4 2H2v20h2v-9h14.2l-5.5 5.5 1.4 1.4L22 12l-8-8-1.3 1.5 5.5 5.5H4V2Z" />
    </g>
  </Icon>
);

export default ArrowExpandRight;
