/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Back15 = (props: Props) => (
  <Icon
    xmlSpace="preserve"
    data-license="Apache License 2.0"
    data-source="Material Design"
    viewBox="0 0 48 48"
    {...props}
  >
    <path d="M21 47.8c-2.8-.4-5.2-1.3-7.7-2.5s-4.5-2.9-6.2-5.1-3-4.6-3.8-7.4l3.4-.9A17.6 17.6 0 0 0 28.3 44a17.6 17.6 0 0 0 12.1-21.6 17.5 17.5 0 0 0-21.6-12.1l-1 .3 5.3 2.9-1.7 3-10.6-5.8L16.7 0l3 1.6-3.1 5.7 1.3-.3a21.8 21.8 0 0 1 22.2 6.9 21.4 21.4 0 0 1-3.2 29.6A20.4 20.4 0 0 1 21 47.8" />
    <path d="M15.4 31.8v-1.9h2.8v-6h-2.3v-1.5l1.2-.2.9-.3.8-.4h1.8v8.4H23v1.9zm13.1.1-1.6-.2a5 5 0 0 1-1.3-.5l-1-.7 1.1-1.5.7.5.8.4.9.1 1-.2.7-.5c.2-.2.3-.5.3-.9 0-.5-.2-.9-.5-1.2-.3-.3-.8-.4-1.3-.4l-.9.1-.9.4-1.1-.7.3-5.2h6.4v2h-4.3l-.2 1.9.7-.2.7-.1 1.8.3c.5.2 1 .6 1.3 1.1s.5 1.1.5 1.8a3.4 3.4 0 0 1-2.1 3.2c-.6.4-1.3.5-2 .5" />
  </Icon>
);
export default Back15;
