/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const CursorClick = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 32 32" {...props}>
    <path
      fill="currentColor"
      d="m15.3 14.7 8.5 7.1-1.1.3-.9.1c-.8.2-1.3 1.1-1 1.9l.4.8 1.8 3.9-1.9.9-1.8-4-.3-.7a1.3 1.3 0 0 0-2-.5l-.7.5-1 .8zm-1-3.1a1 1 0 0 0-1 1v15.3c0 .5.5 1 1 1l.7-.2 2.5-2.1 2.2 4.8c.2.4.6.6 1 .6l.4-.1 3.7-1.7c.5-.3.7-.9.5-1.4L23 24l3.3-.6c.2 0 .4-.2.5-.3.4-.5.3-1.1-.1-1.5L15 11.8a1 1 0 0 0-.7-.2m5.7 1.7v-2.6h6.7v2.6zm-1.6-7 3.8-3.7 1.9 1.9-3.8 3.7zm-5-6.3H16v6.7h-2.7V0ZM5.1 19.5 9 15.8l1.9 1.9L7 21.4zm0-15 2-2 3.7 3.8-1.9 2zm4.1 8.8H2.7v-2.6h6.6v2.6Z"
    />
  </Icon>
);
export default CursorClick;
