/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const ExpandTwoArrows = (props: Props) => (
  <Icon viewBox="0 0 20 20" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path
        fill="currentColor"
        d="M8.3 17.5v-1.7h-3l3.8-3.7-1.2-1.2-3.7 3.8v-3H2.5v5.8h5.8Zm3.8-8.4 3.7-3.8v3h1.7V2.5h-5.8v1.7h3l-3.8 3.7 1.2 1.2Z"
      />
    </g>
  </Icon>
);

export default ExpandTwoArrows;
