/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const ExpandTwoArrows = (props: Props) => (
  <Icon viewBox="0 0 20 20" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path
        d="M8.33333 17.5V15.8333H5.34167L9.09167 12.0833L7.91667 10.9083L4.16667 14.6583V11.6667H2.5V17.5H8.33333ZM12.0833 9.09167L15.8333 5.34167V8.33333H17.5V2.5H11.6667V4.16667H14.6583L10.9083 7.91667L12.0833 9.09167Z"
        fill="currentColor"
      />
    </g>
  </Icon>
);

export default ExpandTwoArrows;
