/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const ExpandTwoArrows = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      d="M8.3 17.5v-1.7h-3l3.8-3.7-1.2-1.2-3.7 3.8v-3H2.5v5.8zm3.8-8.4 3.7-3.8v3h1.7V2.5h-5.8v1.7h3l-3.8 3.7z"
    />
  </Icon>
);
export default ExpandTwoArrows;
