/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const FileCompare = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M10 18H6v-2h4v2m0-4H6v-2h4v2m0-13v1H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h4v1h2V1h-2m10 7v12a2 2 0 0 1-2 2h-4v-2h4v-9h-4V9h4.5L14 4.5V2l6 6m-4 6h-2v-2h2v2m0 4h-2v-2h2v2Z" />
    </g>
  </Icon>
);

export default FileCompare;
