/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const Forward15 = (props: Props) => (
  <Icon viewBox="0 0 48 48" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="M19.4 47.3a20 20 0 0 1-12.5-10 21.2 21.2 0 0 1 1.9-23.4c1.7-2.1 3.8-3.9 6.1-5.1A21.7 21.7 0 0 1 30.8 7l1.3.3L29 1.6 32 0l5.9 10.7-10.6 5.8-1.7-3 5.3-2.9-1-.3c-4.7-1.3-9.2-.7-13.3 1.6s-7 5.8-8.3 10.5-.7 9.1 1.6 13.3c2.3 4.1 5.8 7 10.5 8.3 4.7 1.3 9.1.7 13.3-1.6 4.1-2.3 6.9-5.8 8.3-10.5l3.4.9a20 20 0 0 1-10 12.5 21.8 21.8 0 0 1-16 2z" />
      <path d="M16.1 31.9V30h2.8v-6h-2.3v-1.5l1.2-.2.9-.3.8-.4h1.8V30h2.4v1.9h-7.6zm13.1.1-1.6-.2-1.3-.5-1-.7 1.1-1.5.7.5.8.4.9.1 1-.2.7-.5c.2-.2.3-.5.3-.9 0-.5-.2-.9-.5-1.2-.3-.3-.8-.4-1.3-.4l-.9.1-.9.4-1.1-.7.3-5.2h6.4v2h-4.3l-.2 1.9.7-.2.7-.1 1.8.3c.5.2 1 .6 1.3 1.1s.5 1.1.5 1.8a3.4 3.4 0 0 1-2.1 3.2c-.6.4-1.3.5-2 .5z" />
    </g>
  </Icon>
);

export default Forward15;
