/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React, { ReactNode } from 'react';
import Icon, { Props as IconProps } from '../Icon';

interface Props extends IconProps {
  children?: ReactNode;
}

const GridListView = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path fill="none" d="M0 0h24v24H0z" />
      <path d="M14.7 5v6.5H9.3V5h5.4zm1 6.5H21V5h-5.3v6.5zm-1 7.5v-6.5H9.3V19h5.4zm1-6.5V19H21v-6.5h-5.3zm-7.4 0H3V19h5.3v-6.5zm0-1V5H3v6.5h5.3z" />
    </g>
  </Icon>
);

export default GridListView;
