/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Grid = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M3 9h4V5H3zm0 5h4v-4H3zm5 0h4v-4H8zm5 0h4v-4h-4zM8 9h4V5H8zm5-4v4h4V5zm5 9h4v-4h-4zM3 19h4v-4H3zm5 0h4v-4H8zm5 0h4v-4h-4zm5 0h4v-4h-4zm0-14v4h4V5z" />
    <path fill="none" d="M0 0h24v24H0z" />
  </Icon>
);
export default Grid;
