/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const HeartLine = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M12 4.53a6 6 0 0 1 8.48 8.46L12 21.5 3.52 13A6 6 0 0 1 12 4.53m6.83 1.64a4 4 0 0 0-5.5-.15L12 7.22l-1.33-1.2a4 4 0 0 0-5.69 5.6L12 18.65l7.02-7.03a4 4 0 0 0-.2-5.45" />
  </Icon>
);
export default HeartLine;
