/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const HeartOutline = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Icons" viewBox="0 0 24 24" {...props}>
    <path d="M12.1 18.6h-.2C7 14.2 4 11.4 4 8.5 4 6.5 5.5 5 7.5 5c1.5 0 3 1 3.6 2.4h1.8A4 4 0 0 1 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.9-3.1 5.7-7.9 10M16.5 3A6 6 0 0 0 12 5a6 6 0 0 0-4.5-2C4.5 3 2 5.4 2 8.5c0 3.8 3.4 6.9 8.6 11.5l1.4 1.4 1.4-1.4c5.2-4.6 8.6-7.7 8.6-11.5 0-3-2.4-5.5-5.5-5.5" />
  </Icon>
);
export default HeartOutline;
