/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
export { default as ArrowExpandLeft } from "./ArrowExpandLeft";
export { default as ArrowExpandRight } from "./ArrowExpandRight";
export { default as Back15 } from "./Back15";
export { default as Bookmark } from "./Bookmark";
export { default as BookmarkFill } from "./BookmarkFill";
export { default as Class } from "./Class";
export { default as CloseLine } from "./CloseLine";
export { default as Copy } from "./Copy";
export { default as Cross } from "./Cross";
export { default as CursorClick } from "./CursorClick";
export { default as ExpandLess } from "./ExpandLess";
export { default as ExpandMore } from "./ExpandMore";
export { default as ExpandTwoArrows } from "./ExpandTwoArrows";
export { default as FileCompare } from "./FileCompare";
export { default as FileCopyLine } from "./FileCopyLine";
export { default as FileMarkedFill } from "./FileMarkedFill";
export { default as FileMarkedLine } from "./FileMarkedLine";
export { default as Forward15 } from "./Forward15";
export { default as ForwardArrow } from "./ForwardArrow";
export { default as FourlineHamburger } from "./FourlineHamburger";
export { default as Grid } from "./Grid";
export { default as GridListView } from "./GridListView";
export { default as Heart } from "./Heart";
export { default as HeartOutline } from "./HeartOutline";
export { default as List } from "./List";
export { default as MenuBook } from "./MenuBook";
export { default as Minus } from "./Minus";
export { default as Pencil } from "./Pencil";
export { default as Plus } from "./Plus";
export { default as Print } from "./Print";
export { default as RemoveCircle } from "./RemoveCircle";
export { default as Replay15Line } from "./Replay15Line";
export { default as Reply } from "./Reply";
export { default as RightArrow } from "./RightArrow";
export { default as School } from "./School";
export { default as Thumb } from "./Thumb";
export { default as ThumbFilled } from "./ThumbFilled";
export { default as TrashCanOutline } from "./TrashCanOutline";
