/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from '../Icon';
const List = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path d="M4 14h4v-4H4zm0 5h4v-4H4zM4 9h4V5H4zm5 5h12v-4H9zm0 5h12v-4H9zM9 5v4h12V5z" />
    <path fill="none" d="M0 0h24v24H0z" />
  </Icon>
);
export default List;
