/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const MenuBook = (props: Props) => (
  <Icon data-license="Apache License 2.0" data-source="Material Design" viewBox="0 0 24 24" {...props}>
    <path fill="none" d="M0 0h24v24H0z" />
    <path d="M21 5c-1.1-.3-2.3-.5-3.5-.5-2 0-4 .4-5.5 1.5-1.4-1.1-3.5-1.5-5.5-1.5S2.5 4.9 1 6v14.7c0 .2.3.4.5.4h.3C3 20.4 5 20 6.5 20c2 0 4 .4 5.5 1.5a12 12 0 0 1 5.5-1.5c1.6 0 3.4.3 4.8 1l.2.1c.3 0 .5-.3.5-.5V6c-.6-.5-1.3-.8-2-1m0 13.5a11.6 11.6 0 0 0-9 1V8a11.6 11.6 0 0 1 9-1z" />
    <path d="M17.5 10.5c.9 0 1.7 0 2.5.3V9.2a13.5 13.5 0 0 0-7 .6v1.7c1.1-.7 2.7-1 4.5-1m-4.5 2v1.7c1.1-.7 2.7-1 4.5-1 .9 0 1.7 0 2.5.2V12a13.5 13.5 0 0 0-7 .6zm4.5 1.8c-1.7 0-3.2.3-4.5.9v1.6c1.1-.6 2.7-1 4.5-1 .9 0 1.7.1 2.5.3v-1.5a10 10 0 0 0-2.5-.3" />
  </Icon>
);
export default MenuBook;
