/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import Icon, { Props } from '../Icon';

const RightArrow = (props: Props) => (
  <Icon viewBox="0 0 24 24" data-license="Apache License 2.0" data-source="Material Design" {...props}>
    <g>
      <path d="m8.6 16.3 4.6-4.6-4.6-4.5L10 5.7l6 6-6 6z" />
      <path fill="none" d="M0-.3h24v24H0z" />
    </g>
  </Icon>
);

export default RightArrow;
