/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const ThumbFilled = (props: Props) => (
  <Icon fill="none" viewBox="0 0 18 15" {...props}>
    <path
      fill="currentColor"
      d="M9.82.5 5.78 4.54c-.27.27-.43.64-.43 1.03v7.28c0 .8.66 1.46 1.46 1.46h6.56c.59 0 1.11-.35 1.35-.88l2.37-5.55a2.2 2.2 0 0 0-2-3.05h-4.13l.7-3.34a1.08 1.08 0 0 0-1.84-1M2.44 14.31c.8 0 1.46-.65 1.46-1.46V7.02a1.46 1.46 0 0 0-2.92 0v5.83c0 .8.65 1.46 1.46 1.46"
    />
  </Icon>
);
export default ThumbFilled;
