/**
 * Copyright (c) 2021-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { Props } from "../Icon";
const Thumb = (props: Props) => (
  <Icon fill="none" viewBox="0 0 18 18" {...props}>
    <path
      fill="currentColor"
      d="M15.56 6.08h-4.6l.7-3.33.02-.23c0-.3-.13-.58-.33-.78l-.77-.76-4.8 4.8c-.27.27-.43.63-.43 1.03v7.3c0 .8.66 1.45 1.46 1.45h6.56c.61 0 1.13-.36 1.35-.89l2.2-5.14c.06-.17.1-.34.1-.53V7.54c0-.8-.66-1.46-1.46-1.46m0 2.92-2.19 5.1H6.81V6.81l3.17-3.16-.81 3.9h6.4zM.98 6.81H3.9v8.75H.98z"
    />
  </Icon>
);
export default Thumb;
