/**
 * Copyright (c) 2024-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */
// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import Icon, { type Props } from "../Icon";
const ArrowUpDoubleLine = (props: Props) => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="m12 4.84-6.2 6.2 1.4 1.42 4.8-4.8 4.8 4.8 1.4-1.42zm0 5.65-6.2 6.2 1.4 1.42 4.8-4.8 4.8 4.8 1.4-1.42z" />
  </Icon>
);
export default ArrowUpDoubleLine;
