/**
 * Copyright (c) 2025-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const MenuSearchLine = (props: Props): JSX.Element => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M15.5 5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7M10 8.5a5.5 5.5 0 1 1 10.03 3.12l2.68 2.67-1.42 1.42-2.67-2.68A5.5 5.5 0 0 1 10 8.5M3 4h5v2H3zm0 7h5v2H3zm18 7v2H3v-2z" />
  </Icon>
);
