/**
 * Copyright (c) 2025-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const MovieLine = (props: Props): JSX.Element => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M2 4a1 1 0 0 1 1-1h18a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1zm2 1v14h16V5zm6.62 3.41 4.88 3.26a.4.4 0 0 1 0 .66l-4.88 3.26a.4.4 0 0 1-.62-.34v-6.5a.4.4 0 0 1 .62-.34" />
  </Icon>
);
