/**
 * Copyright (c) 2025-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const SettingsLine = (props: Props): JSX.Element => (
  <Icon fill="currentColor" data-license="Apache License 2.0" data-source="RemixIcon" viewBox="0 0 24 24" {...props}>
    <path d="M2 12c0-.86.11-1.7.32-2.5a3 3 0 0 0 2.67-4.63 9.99 9.99 0 0 1 4.34-2.5 3 3 0 0 0 5.34 0 9.99 9.99 0 0 1 4.34 2.5 3 3 0 0 0 2.67 4.63 10.02 10.02 0 0 1 0 5 3 3 0 0 0-2.67 4.63 9.99 9.99 0 0 1-4.34 2.5 3 3 0 0 0-5.34 0 9.99 9.99 0 0 1-4.34-2.5 3 3 0 0 0-2.67-4.63A9.42 9.42 0 0 1 2 12m4.8 3a5 5 0 0 1 .57 3.52c.4.3.84.55 1.3.75a5 5 0 0 1 6.67 0c.45-.2.88-.46 1.3-.75a5 5 0 0 1 3.33-5.77 8.14 8.14 0 0 0 0-1.5 5 5 0 0 1-3.34-5.77 8 8 0 0 0-1.3-.75 5 5 0 0 1-6.67 0c-.45.2-.88.46-1.3.75a5 5 0 0 1-3.33 5.77 8.13 8.13 0 0 0 0 1.5A5 5 0 0 1 6.8 15m5.2 0a3 3 0 1 1 0-6 3 3 0 0 1 0 6m0-2a1 1 0 1 0 0-2 1 1 0 0 0 0 2" />
  </Icon>
);
