/**
 * Copyright (c) 2025-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT;
import type { JSX } from "react";
import { Icon, type Props } from "../Icon";
export const ThumbFilled = (props: Props): JSX.Element => (
  <Icon fill="currentColor" viewBox="0 -960 960 960" {...props}>
    <path d="M720-120H320v-520l280-280 50 50q7 7 11.5 19t4.5 23v14l-44 174h218q32 0 56 24t24 56v80q0 7-1.5 15t-4.5 15L794-168q-9 20-30 34t-44 14M240-640v520H80v-520z" />
  </Icon>
);
