/**
 * Copyright (c) 2017-present, NDLA.
 *
 * This source code is licensed under the GPLv3 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

// N.B! AUTOGENERATED FILE. DO NOT EDIT
import React from 'react';
import Icon from '../Icon';

const ExpandMore = props => (
  <Icon viewBox="0 0 48 48" data-license="CC-BY 4.0" {...props}>
    <g>
      <path d="M33.17 17.17L24 26.34l-9.17-9.17L12 20l12 12 12-12z" />
    </g>
  </Icon>
);

export default ExpandMore;
